# APH/PPH split propotions artifact vs csv

## Setup

In [ ]:
import pandas as pd, numpy as np, os
from vivarium import Artifact
import db_queries
from get_draws.api import get_draws
import matplotlib.pyplot as plt
from pathlib import Path
import yaml
from vivarium_gates_mncnh.constants import paths

In [ ]:
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)

In [ ]:
# Parameters cell for papermill
model_dir = "model34.0"

In [ ]:
base_artifacts_dir = Path("/mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/") / model_dir

In [ ]:
artifact_paths = {p.stem.title(): p for p in base_artifacts_dir.iterdir()}
artifact_paths

In [ ]:
locations = list(artifact_paths.keys())
locations

In [ ]:
location_ids = db_queries.get_ids('location')
location_ids = location_ids.loc[location_ids.location_name.str.lower().isin([x.lower() for x in locations])]
location_ids

In [ ]:
def load_yaml_file(path):
    with open(path) as stream:
        return yaml.safe_load(stream)

In [ ]:
def read_artifact(key, filter_terms=['sex == Female' , 'age_start > 5', 'age_end < 60']):
    all_locations_data = []
    for location in locations:
        art = Artifact(artifact_paths[location], filter_terms=filter_terms)
        location_data = art.load(key)
        if not isinstance(location_data, pd.DataFrame):
            location_data = pd.DataFrame({'value': location_data, 'location': location}, index=[0]).set_index('location')
        else:
            location_data['location'] = location
            location_data = location_data.reset_index().set_index(['location'] + [c for c in location_data.index.names if c is not None])
        all_locations_data.append(location_data)

    all_locations_data = pd.concat(all_locations_data)
    #if 'draw' in all_locations_data.columns[0]:
    #    all_locations_data = all_locations_data[[f'draw_{draw}' for draw in draws]]
    #else:
    #    for draw in draws:
    #        all_locations_data[f'draw_{draw}'] = all_locations_data['value']
    #    all_locations_data = all_locations_data.drop(columns='value')
    return all_locations_data

In [24]:
pp_frac = read_artifact('cause.maternal_hemorrhage.postpartum_fraction')
pp_frac

                                                         draw_0    draw_1  \
location sex    age_start age_end year_start year_end
Nigeria  Female 10.0      15.0    2023       2024      0.444326  0.247066
                15.0      20.0    2023       2024      0.503615  0.625949
                20.0      25.0    2023       2024      0.611507  0.545196
                25.0      30.0    2023       2024      0.535381  0.560420
                30.0      35.0    2023       2024      0.671430  0.685059
                35.0      40.0    2023       2024      0.641927  0.754158
                40.0      45.0    2023       2024      0.789855  0.478396
                45.0      50.0    2023       2024      0.765985  0.802746
                50.0      55.0    2023       2024      0.353528  0.489413
Pakistan Female 10.0      15.0    2023       2024      0.444326  0.247066
                15.0      20.0    2023       2024      0.503615  0.625949
                20.0      25.0    2023       2024      0.611507  0.545196
                25.0      30.0    2023       2024      0.535381  0.560420
                30.0      35.0    2023       2024      0.671430  0.685059
                35.0      40.0    2023       2024      0.641927  0.754158
                40.0      45.0    2023       2024      0.789855  0.478396
                45.0      50.0    2023       2024      0.765985  0.802746
                50.0      55.0    2023       2024      0.353528  0.489413
Ethiopia Female 10.0      15.0    2023       2024      0.444326  0.247066
                15.0      20.0    2023       2024      0.503615  0.625949
                20.0      25.0    2023       2024      0.611507  0.545196
                25.0      30.0    2023       2024      0.535381  0.560420
                30.0      35.0    2023       2024      0.671430  0.685059
                35.0      40.0    2023       2024      0.641927  0.754158
                40.0      45.0    2023       2024      0.789855  0.478396
                45.0      50.0    2023       2024      0.765985  0.802746
                50.0      55.0    2023       2024      0.353528  0.489413

                                                         draw_2    draw_3  \
location sex    age_start age_end year_start year_end
Nigeria  Female 10.0      15.0    2023       2024      0.427258  0.283468
                15.0      20.0    2023       2024      0.372444  0.538477
                20.0      25.0    2023       2024      0.655536  0.610132
                25.0      30.0    2023       2024      0.519573  0.372675
                30.0      35.0    2023       2024      0.547801  0.582583
                35.0      40.0    2023       2024      0.566184  0.804289
                40.0      45.0    2023       2024      0.887804  0.370323
                45.0      50.0    2023       2024      1.000000  0.267751
                50.0      55.0    2023       2024      0.567095  0.475411
Pakistan Female 10.0      15.0    2023       2024      0.427258  0.283468
                15.0      20.0    2023       2024      0.372444  0.538477
                20.0      25.0    2023       2024      0.655536  0.610132
                25.0      30.0    2023       2024      0.519573  0.372675
                30.0      35.0    2023       2024      0.547801  0.582583
                35.0      40.0    2023       2024      0.566184  0.804289
                40.0      45.0    2023       2024      0.887804  0.370323
                45.0      50.0    2023       2024      1.000000  0.267751
                50.0      55.0    2023       2024      0.567095  0.475411
Ethiopia Female 10.0      15.0    2023       2024      0.427258  0.283468
                15.0      20.0    2023       2024      0.372444  0.538477
                20.0      25.0    2023       2024      0.655536  0.610132
                25.0      30.0    2023       2024      0.519573  0.372675
                30.0      35.0    2023       2024      0.547801  0.582583
                35.0      40.0    2023       2024      0.566184  0.804289
                40.0      45.0    2023       2024      0.887804  0.370323
                45.0      50.0    2023       2024      1.000000  0.267751
                50.0      55.0    2023       2024      0.567095  0.475411

                                                         draw_4    draw_5  \
location sex    age_start age_end year_start year_end
Nigeria  Female 10.0      15.0    2023       2024      0.375719  0.258482
                15.0      20.0    2023       2024      0.497887  0.407265
                20.0      25.0    2023       2024      0.512095  0.724680
                25.0      30.0    2023       2024      0.779196  0.684471
                30.0      35.0    2023       2024      0.455540  0.751652
                35.0      40.0    2023       2024      0.692228  0.647926
                40.0      45.0    2023       2024      0.429536  0.411325
                45.0      50.0    2023       2024      0.574202  0.736391
                50.0      55.0    2023       2024      0.534370  0.467622
Pakistan Female 10.0      15.0    2023       2024      0.375719  0.258482
                15.0      20.0    2023       2024      0.497887  0.407265
                20.0      25.0    2023       2024      0.512095  0.724680
                25.0      30.0    2023       2024      0.779196  0.684471
                30.0      35.0    2023       2024      0.455540  0.751652
                35.0      40.0    2023       2024      0.692228  0.647926
                40.0      45.0    2023       2024      0.429536  0.411325
                45.0      50.0    2023       2024      0.574202  0.736391
                50.0      55.0    2023       2024      0.534370  0.467622
Ethiopia Female 10.0      15.0    2023       2024      0.375719  0.258482
                15.0      20.0    2023       2024      0.497887  0.407265
                20.0      25.0    2023       2024      0.512095  0.724680
                25.0      30.0    2023       2024      0.779196  0.684471
                30.0      35.0    2023       2024      0.455540  0.751652
                35.0      40.0    2023       2024      0.692228  0.647926
                40.0      45.0    2023       2024      0.429536  0.411325
                45.0      50.0    2023       2024      0.574202  0.736391
                50.0      55.0    2023       2024      0.534370  0.467622

                                                         draw_6    draw_7  \
location sex    age_start age_end year_start year_end
Nigeria  Female 10.0      15.0    2023       2024      0.341687  0.613255
                15.0      20.0    2023       2024      0.497463  0.426163
                20.0      25.0    2023       2024      0.641279  0.483317
                25.0      30.0    2023       2024      0.477594  0.419750
                30.0      35.0    2023       2024      0.620694  0.419959
                35.0      40.0    2023       2024      0.465429  0.521874
                40.0      45.0    2023       2024      0.830375  0.448914
                45.0      50.0    2023       2024      0.636511  0.422667
                50.0      55.0    2023       2024      0.492564  0.426775
Pakistan Female 10.0      15.0    2023       2024      0.341687  0.613255
                15.0      20.0    2023       2024      0.497463  0.426163
                20.0      25.0    2023       2024      0.641279  0.483317
                25.0      30.0    2023       2024      0.477594  0.419750
                30.0      35.0    2023       2024      0.620694  0.419959
                35.0      40.0    2023       2024      0.465429  0.521874
                40.0      45.0    2023       2024      0.830375  0.448914
                45.0      50.0    2023       2024      0.636511  0.422667
                50.0      55.0    2023       2024      0.492564  0.426775
Ethiopia Female 10.0      15.0    2023       2024      0.341687  0.613255
                15.0      20.0    2023       2024      0.497463  0.426163
                20.0      25.0    2023       2024      0.641279  0.483317
                25.0      30.0    2023       2024      0.477594  0.419750
                30.0      35.0    2023       2024      0.620694  0.419959
                35.0      40.0    2023       2024      0.465429  0.521874
                40.0      45.0    2023       2024      0.830375  0.448914
                45.0      50.0    2023       2024      0.636511  0.422667
                50.0      55.0    2023       2024      0.492564  0.426775

                                                         draw_8    draw_9  \
location sex    age_start age_end year_start year_end
Nigeria  Female 10.0      15.0    2023       2024      0.654526  0.566229
                15.0      20.0    2023       2024      0.477926  0.403805
                20.0      25.0    2023       2024      0.425888  0.610977
                25.0      30.0    2023       2024      0.431730  0.617662
                30.0      35.0    2023       2024      0.609352  0.665587
                35.0      40.0    2023       2024      0.647854  0.415363
                40.0      45.0    2023       2024      0.392268  0.512427
                45.0      50.0    2023       2024      1.000000  0.188527
                50.0      55.0    2023       2024      0.515060  0.408191
Pakistan Female 10.0      15.0    2023       2024      0.654526  0.566229
                15.0      20.0    2023       2024      0.477926  0.403805
                20.0      25.0    2023       2024      0.425888  0.610977
                25.0      30.0    2023       2024      0.431730  0.617662
                30.0      35.0    2023       2024      0.609352  0.665587
                35.0      40.0    2023       2024      0.647854  0.415363
                40.0      45.0    2023       2024      0.392268  0.512427
                45.0      50.0    2023       2024      1.000000  0.188527
                50.0      55.0    2023       2024      0.515060  0.408191
Ethiopia Female 10.0      15.0    2023       2024      0.654526  0.566229
                15.0      20.0    2023       2024      0.477926  0.403805
                20.0      25.0    2023       2024      0.425888  0.610977
                25.0      30.0    2023       2024      0.431730  0.617662
                30.0      35.0    2023       2024      0.609352  0.665587
                35.0      40.0    2023       2024      0.647854  0.415363
                40.0      45.0    2023       2024      0.392268  0.512427
                45.0      50.0    2023       2024      1.000000  0.188527
                50.0      55.0    2023       2024      0.515060  0.408191

                                                       ...  draw_240  \
location sex    age_start age_end year_start year_end  ...
Nigeria  Female 10.0      15.0    2023       2024      ...  0.369717
                15.0      20.0    2023       2024      ...  0.543896
                20.0      25.0    2023       2024      ...  0.416751
                25.0      30.0    2023       2024      ...  0.461576
                30.0      35.0    2023       2024      ...  0.371243
                35.0      40.0    2023       2024      ...  0.584585
                40.0      45.0    2023       2024      ...  0.752243
                45.0      50.0    2023       2024      ...  1.000000
                50.0      55.0    2023       2024      ...  0.521410
Pakistan Female 10.0      15.0    2023       2024      ...  0.369717
                15.0      20.0    2023       2024      ...  0.543896
                20.0      25.0    2023       2024      ...  0.416751
                25.0      30.0    2023       2024      ...  0.461576
                30.0      35.0    2023       2024      ...  0.371243
                35.0      40.0    2023       2024      ...  0.584585
                40.0      45.0    2023       2024      ...  0.752243
                45.0      50.0    2023       2024      ...  1.000000
                50.0      55.0    2023       2024      ...  0.521410
Ethiopia Female 10.0      15.0    2023       2024      ...  0.369717
                15.0      20.0    2023       2024      ...  0.543896
                20.0      25.0    2023       2024      ...  0.416751
                25.0      30.0    2023       2024      ...  0.461576
                30.0      35.0    2023       2024      ...  0.371243
                35.0      40.0    2023       2024      ...  0.584585
                40.0      45.0    2023       2024      ...  0.752243
                45.0      50.0    2023       2024      ...  1.000000
                50.0      55.0    2023       2024      ...  0.521410

                                                       draw_241  draw_242  \
location sex    age_start age_end year_start year_end
Nigeria  Female 10.0      15.0    2023       2024      0.255701  0.507374
                15.0      20.0    2023       2024      0.404021  0.493226
                20.0      25.0    2023       2024      0.515146  0.508562
                25.0      30.0    2023       2024      0.515579  0.329965
                30.0      35.0    2023       2024      0.558606  0.624109
                35.0      40.0    2023       2024      0.703971  0.544123
                40.0      45.0    2023       2024      0.741036  0.550576
                45.0      50.0    2023       2024      0.572702  0.338492
                50.0      55.0    2023       2024      0.442649  0.413676
Pakistan Female 10.0      15.0    2023       2024      0.255701  0.507374
                15.0      20.0    2023       2024      0.404021  0.493226
                20.0      25.0    2023       2024      0.515146  0.508562
                25.0      30.0    2023       2024      0.515579  0.329965
                30.0      35.0    2023       2024      0.558606  0.624109
                35.0      40.0    2023       2024      0.703971  0.544123
                40.0      45.0    2023       2024      0.741036  0.550576
                45.0      50.0    2023       2024      0.572702  0.338492
                50.0      55.0    2023       2024      0.442649  0.413676
Ethiopia Female 10.0      15.0    2023       2024      0.255701  0.507374
                15.0      20.0    2023       2024      0.404021  0.493226
                20.0      25.0    2023       2024      0.515146  0.508562
                25.0      30.0    2023       2024      0.515579  0.329965
                30.0      35.0    2023       2024      0.558606  0.624109
                35.0      40.0    2023       2024      0.703971  0.544123
                40.0      45.0    2023       2024      0.741036  0.550576
                45.0      50.0    2023       2024      0.572702  0.338492
                50.0      55.0    2023       2024      0.442649  0.413676

                                                       draw_243  draw_244  \
location sex    age_start age_end year_start year_end
Nigeria  Female 10.0      15.0    2023       2024      0.389305  0.374576
                15.0      20.0    2023       2024      0.431943  0.694221
                20.0      25.0    2023       2024      0.486978  0.434163
                25.0      30.0    2023       2024      0.340021  0.446515
                30.0      35.0    2023       2024      0.455971  0.476379
                35.0      40.0    2023       2024      0.484077  0.393285
                40.0      45.0    2023       2024      0.465090  0.454969
                45.0      50.0    2023       2024      0.807205  0.995690
                50.0      55.0    2023       2024      0.538936  0.353929
Pakistan Female 10.0      15.0    2023       2024      0.389305  0.374576
                15.0      20.0    2023       2024      0.431943  0.694221
                20.0      25.0    2023       2024      0.486978  0.434163
                25.0      30.0    2023       2024      0.340021  0.446515
                30.0      35.0    2023       2024      0.455971  0.476379
                35.0      40.0    2023       2024      0.484077  0.393285
                40.0      45.0    2023       2024      0.465090  0.454969
                45.0      50.0    2023       2024      0.807205  0.995690
                50.0      55.0    2023       2024      0.538936  0.353929
Ethiopia Female 10.0      15.0    2023       2024      0.389305  0.374576
                15.0      20.0    2023       2024      0.431943  0.694221
                20.0      25.0    2023       2024      0.486978  0.434163
                25.0      30.0    2023       2024      0.340021  0.446515
                30.0      35.0    2023       2024      0.455971  0.476379
                35.0      40.0    2023       2024      0.484077  0.393285
                40.0      45.0    2023       2024      0.465090  0.454969
                45.0      50.0    2023       2024      0.807205  0.995690
                50.0      55.0    2023       2024      0.538936  0.353929

                                                       draw_245  draw_246  \
location sex    age_start age_end year_start year_end
Nigeria  Female 10.0      15.0    2023       2024      0.370623  0.332463
                15.0      20.0    2023       2024      0.621681  0.675559
                20.0      25.0    2023       2024      0.533524  0.568354
                25.0      30.0    2023       2024      0.687173  0.475330
                30.0      35.0    2023       2024      0.465262  0.697382
                35.0      40.0    2023       2024      0.681393  0.485479
                40.0      45.0    2023       2024      0.623401  0.387987
                45.0      50.0    2023       2024      0.777655  0.527445
                50.0      55.0    2023       2024      0.505036  0.376564
Pakistan Female 10.0      15.0    2023       2024      0.370623  0.332463
                15.0      20.0    2023       2024      0.621681  0.675559
                20.0      25.0    2023       2024      0.533524  0.568354
                25.0      30.0    2023       2024      0.687173  0.475330
                30.0      35.0    2023       2024      0.465262  0.697382
                35.0      40.0    2023       2024      0.681393  0.485479
                40.0      45.0    2023       2024      0.623401  0.387987
                45.0      50.0    2023       2024      0.777655  0.527445
                50.0      55.0    2023       2024      0.505036  0.376564
Ethiopia Female 10.0      15.0    2023       2024      0.370623  0.332463
                15.0      20.0    2023       2024      0.621681  0.675559
                20.0      25.0    2023       2024      0.533524  0.568354
                25.0      30.0    2023       2024      0.687173  0.475330
                30.0      35.0    2023       2024      0.465262  0.697382
                35.0      40.0    2023       2024      0.681393  0.485479
                40.0      45.0    2023       2024      0.623401  0.387987
                45.0      50.0    2023       2024      0.777655  0.527445
                50.0      55.0    2023       2024      0.505036  0.376564

                                                       draw_247  draw_248  \
location sex    age_start age_end year_start year_end
Nigeria  Female 10.0      15.0    2023       2024      0.565966  0.268203
                15.0      20.0    2023       2024      0.436900  0.547164
                20.0      25.0    2023       2024      0.442476  0.434801
                25.0      30.0    2023       2024      0.657951  0.735855
                30.0      35.0    2023       2024      0.772096  0.747864
                35.0      40.0    2023       2024      0.512631  0.592187
                40.0      45.0    2023       2024      0.508517  0.777389
                45.0      50.0    2023       2024      0.236565  0.367240
                50.0      55.0    2023       2024      0.489167  0.501805
Pakistan Female 10.0      15.0    2023       2024      0.565966  0.268203
                15.0      20.0    2023       2024      0.436900  0.547164

In [25]:
def describe_rowwise(df, percentiles=(0.025, 0.975)):
    # The pandas .describe() method describes columns
    # We can transpose before and after to describe rows instead
    return df.transpose().describe(percentiles=percentiles).transpose()

In [26]:
art = describe_rowwise(np.log(pp_frac))[["mean", "std"]].reset_index()
art = art[art.location == "Nigeria"].drop(columns=["location", "year_start", "year_end"]).set_index(["age_start", "age_end", "sex"])
art

                              mean       std
age_start age_end sex
10.0      15.0    Female -0.822753  0.314612
15.0      20.0    Female -0.733140  0.199369
20.0      25.0    Female -0.637200  0.198696
25.0      30.0    Female -0.595011  0.210849
30.0      35.0    Female -0.594911  0.235628
35.0      40.0    Female -0.605281  0.209399
40.0      45.0    Female -0.652818  0.338083
45.0      50.0    Female -0.768003  0.484397
50.0      55.0    Female -0.691293  0.161889

In [27]:
csv = pd.read_csv(paths.PPH_CROSSWALK_PARAMETERS_CSV)
csv = csv.set_index(["age_start", "age_end", "sex"])
csv = csv.rename(columns={"pred_diff_mean": "mean", "pred_diff_sd": "std"})
csv

                              mean       std
age_start age_end sex
10.0      15.0    Female -0.829067  0.314744
15.0      20.0    Female -0.729488  0.188411
20.0      25.0    Female -0.636943  0.181245
25.0      30.0    Female -0.593641  0.213088
30.0      35.0    Female -0.601271  0.229882
35.0      40.0    Female -0.627765  0.210128
40.0      45.0    Female -0.666090  0.311027
45.0      50.0    Female -0.706105  0.549234
50.0      55.0    Female -0.679698  0.165991

In [28]:
art / csv

                              mean       std
age_start age_end sex
10.0      15.0    Female  0.992385  0.999579
15.0      20.0    Female  1.005006  1.058160
20.0      25.0    Female  1.000404  1.096282
25.0      30.0    Female  1.002307  0.989492
30.0      35.0    Female  0.989422  1.024994
35.0      40.0    Female  0.964184  0.996530
40.0      45.0    Female  0.980075  1.086991
45.0      50.0    Female  1.087661  0.881950
50.0      55.0    Female  1.017058  0.975288