In [56]:
from vivarium import Artifact, InteractiveContext
import pandas as pd, numpy as np, os

In [57]:
! pip list | grep vivarium

# [software verion + hash . date]

vivarium                                 4.0.3
vivarium_build_utils                     3.2.2
vivarium_cluster_tools                   3.1.6
vivarium-compat                          0.6.1
vivarium-dependencies                    1.1.0
vivarium_gates_mncnh                     34.1.dev8+g5eaecaf6f.d20260616 /mnt/share/homes/tylerdy/vivarium_gates_mncnh
vivarium-gbd-mapping                     6.0.1
vivarium_public_health                   5.0.2
vivarium-risk-distributions              3.1.1
vivarium_testing_utils                   0.5.5

In [58]:
! pip freeze | grep vivarium

vivarium==4.0.3
vivarium-compat==0.6.1
vivarium-dependencies==1.1.0
vivarium-gbd-mapping==6.0.1
vivarium-risk-distributions==3.1.1
vivarium_build_utils==3.2.2
vivarium_cluster_tools==3.1.6
-e git+https://github.com/ihmeuw/vivarium_gates_mncnh.git@b8529324faa31aaec00743419d131f765203a25a#egg=vivarium_gates_mncnh
vivarium_public_health==5.0.2
vivarium_testing_utils==0.5.5

In [59]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

from vivarium import InteractiveContext, Artifact

In [60]:
import vivarium_gates_mncnh
from vivarium.framework.configuration import build_model_specification
from pathlib import Path

from vivarium_gates_mncnh.constants.data_values import (
    SIMULATION_EVENT_NAMES,
    COLUMNS,
    PREGNANCY_OUTCOMES,
    PIPELINES,
)

path = Path(vivarium_gates_mncnh.__file__).parent / 'model_specifications/model_spec.yaml'
custom_model_specification = build_model_specification(path)
custom_model_specification.configuration.input_data.input_draw_number = 60

custom_model_specification.configuration.population.population_size = 20_000 * 3

included_components = custom_model_specification.components.vivarium_gates_mncnh.components
included_components

['Hemoglobin()',
 'AnemiaInterventionPropensity()',
 'AgelessPopulation("population.scaling_factor")',
 'Pregnancy()',
 'ResultsStratifier()',
 'ANCAttendance()',
 'Ultrasound()',
 'MaternalDisorder("maternal_obstructed_labor_and_uterine_rupture")',
 'MaternalDisorder("maternal_hemorrhage")',
 'MaternalDisorder("maternal_sepsis_and_other_maternal_infections")',
 'ResidualMaternalDisorders()',
 'AbortionMiscarriageEctopicPregnancy()',
 'MaternalDisordersBurden()',
 'LBWSGRisk()',
 "LBWSGRiskEffect('cause.all_causes.all_cause_mortality_risk')",
 "LBWSGRiskEffect('cause.neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk')",
 "LBWSGRiskEffect('cause.neonatal_preterm_birth_with_rds.cause_specific_mortality_risk')",
 "LBWSGRiskEffect('cause.neonatal_preterm_birth_without_rds.cause_specific_mortality_risk')",
 "LBWSGRiskEffect('cause.neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk')",
 "PretermBirth('neonatal_preterm_birth_with_rds')",
 "PretermBirth('neonatal_preterm_birth_without_rds')",
 "NeonatalCause('neonatal_sepsis_and_other_neonatal_infections')",
 "NeonatalCause('neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma')",
 'NeonatalMortality()',
 'CPAPAndACSRiskEffect()',
 "InterventionRiskEffect('antibiotics')",
 "InterventionRiskEffect('probiotics')",
 "InterventionRiskEffect('azithromycin')",
 "InterventionRiskEffect('misoprostol')",
 'OralIronInterventionExposure()',
 'OralIronEffectOnHemoglobin()',
 'OralIronEffectOnStillbirth()',
 "AdditiveRiskEffect('risk_factor.iron_folic_acid_supplementation', 'risk_factor.birth_weight.birth_exposure')",
 "AdditiveRiskEffect('risk_factor.multiple_micronutrient_supplementation', 'risk_factor.birth_weight.birth_exposure')",
 'OralIronEffectsOnGestationalAge()',
 'IVIronExposure()',
 'IVIronEffectOnHemoglobin()',
 'IVIronEffectOnLBWSG()',
 'IVIronEffectOnStillbirth()',
 'SepsisEffectsOnHemoglobin()',
 'DeliveryFacility()',
 "InterventionAccess('cpap')",
 "InterventionAccess('antibiotics')",
 "InterventionAccess('probiotics')",
 "InterventionAccess('azithromycin')",
 "InterventionAccess('misoprostol')",
 'ACSAccess()',
 'PostpartumDepression()',
 "HemoglobinRiskEffect('risk_factor.hemoglobin', 'cause.maternal_hemorrhage.incidence_risk')",
 "HemoglobinRiskEffect('risk_factor.hemoglobin', 'cause.maternal_sepsis_and_other_maternal_infections.incidence_risk')",
 'CorrelatedPropensities()',
 'AnemiaScreening()',
 'ANCHemoglobinObserver()',
 'ANCOtherObserver()',
 'BirthObserver()',
 'MaternalDisordersBurdenObserver()',
 'NeonatalBurdenObserver()',
 'AnemiaYLDsObserver()',
 'NeonatalCauseRelativeRiskObserver()',
 "InterventionObserver('cpap')",
 "InterventionObserver('antibiotics')",
 "InterventionObserver('probiotics')",
 "InterventionObserver('azithromycin')",
 "InterventionObserver('misoprostol')",
 'PostpartumDepressionObserver()',
 'NeonatalACMRiskObserver()',
 'NeonatalCSMRiskObserver()',
 'ImpossibleNeonatalCSMRiskObserver()']

In [61]:
artifact_path = custom_model_specification.configuration.input_data.artifact_path
art = Artifact(artifact_path)

artifact_path

'/mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/model37.0/ethiopia.hdf'

In [62]:
draw_num = custom_model_specification.configuration.input_data.input_draw_number
draw = 'draw_' + str(draw_num)
draw

'draw_60'

CHECK: puerperal sepsis hemoglobin effect size in the artifact does not vary by sex, age, or year.

Suite: artifact tests.

Type: precise assert.

In [63]:
sepsis_on_hemoglobin_shift = art.load("cause.maternal_sepsis_and_other_maternal_infections.hemoglobin_shift")[draw]
assert len(sepsis_on_hemoglobin_shift) == 2  # early and late postpartum
sepsis_on_hemoglobin_shift

postpartum_period
early_postpartum   -13.247920
late_postpartum     -3.042343
Name: draw_60, dtype: float64

In [ ]:
def check_hemoglobin_shift(sim: InteractiveContext):
    pop = sim.get_population([COLUMNS.MATERNAL_SEPSIS, COLUMNS.PREGNANCY_OUTCOME])
    # We model maternal sepsis on live and still births only
    live_births = pop.loc[
        (pop[COLUMNS.PREGNANCY_OUTCOME] == PREGNANCY_OUTCOMES.LIVE_BIRTH_OUTCOME) |
        (pop[COLUMNS.PREGNANCY_OUTCOME] == PREGNANCY_OUTCOMES.STILLBIRTH_OUTCOME)
    ]
    has_sepsis = live_births[COLUMNS.MATERNAL_SEPSIS]
    sepsis_idx = live_births.index[has_sepsis]
    no_sepsis_idx = live_births.index[~has_sepsis]
    if len(sepsis_idx) == 0:
        return
    # Get hemoglobin exposure values from the pipeline
    hgb = sim.get_population(PIPELINES.HEMOGLOBIN_EXPOSURE).loc[live_births.index]
    mean_hgb_sepsis = hgb.loc[sepsis_idx].mean()
    mean_hgb_no_sepsis = hgb.loc[no_sepsis_idx].mean()

    # is step name the next step to run or the last step which was run? i couldnt check the hemoglobin exposure pipline when
    # steps_remaining was 0
    return {'step': sim._clock.step_name, 'mean_hgb_sepsis': mean_hgb_sepsis, 'mean_hgb_no_sepsis': mean_hgb_no_sepsis}
    # Sepsis shift is negative, so sepsis group should have lower hemoglobin
    #observed_diff = mean_hgb_sepsis - mean_hgb_no_sepsis
    #display(f"{sim._clock.step_name}: ({mean_hgb_sepsis} - {mean_hgb_no_sepsis}) = {observed_diff}")

    # TODO check for age groups as well

In [65]:
def run_all_steps(sim: InteractiveContext):
    step_shifts = []
    while sim.get_number_of_steps_remaining() > 0:
        step_shift = check_hemoglobin_shift(sim)
        if step_shift:
            step_shifts.append(step_shift)
        sim.step()
    return pd.DataFrame(step_shifts)

In [66]:
def run_to_step(sim: InteractiveContext, step_name: str):
    while sim._clock.step_name != step_name:
        sim.step()
    return sim

In [67]:
sim = InteractiveContext(custom_model_specification)
step_shifts = run_all_steps(sim)

2026-07-23 09:52:19.500 | INFO     | simulation_4-artifact_manager:80 - Running simulation from artifact located at /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/model37.0/ethiopia.hdf.
2026-07-23 09:52:19.502 | INFO     | simulation_4-artifact_manager:81 - Artifact base filter terms are ['draw == 60'].
2026-07-23 09:52:19.503 | INFO     | simulation_4-artifact_manager:82 - Artifact additional filter terms are None.

2026-07-23 09:52:50.742 | WARNING  | simulation_4-results_manager:409 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']
2026-07-23 09:52:50.744 | WARNING  | simulation_4-results_manager:409 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']
2026-07-23 09:52:50.913 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'exposure' during setup.
2026-07-23 09:52:50.914 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'ensemble_distribution_weights' during setup.
2026-07-23 09:52:50.914 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_factor.hemoglobin' configured, but didn't build lookup table 'exposure_standard_deviation' during setup.
2026-07-23 09:52:50.915 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'exposure' during setup.
2026-07-23 09:52:50.915 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'ensemble_distribution_weights' during setup.
2026-07-23 09:52:50.916 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'exposure_standard_deviation' during setup.
2026-07-23 09:52:50.917 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_factor.low_birth_weight_and_short_gestation' configured, but didn't build lookup table 'birth_exposure' during setup.
2026-07-23 09:52:50.918 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.all_causes.all_cause_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.
2026-07-23 09:52:50.918 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_sepsis_and_other_neonatal_infections.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.
2026-07-23 09:52:50.919 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_with_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.
2026-07-23 09:52:50.920 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_preterm_birth_without_rds.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.
2026-07-23 09:52:50.920 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'risk_effect.low_birth_weight_and_short_gestation_on_cause.neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma.cause_specific_mortality_risk' configured, but didn't build lookup table 'relative_risk' during setup.
2026-07-23 09:52:50.921 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.maternal_hemorrhage.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.
2026-07-23 09:52:50.922 | WARNING  | simulation_4-lookup_table_manager:85 - Component 'non_log_linear_risk_effect.hemoglobin_on_cause.maternal_sepsis_and_other_maternal_infections.incidence_risk' configured, but didn't build lookup table 'population_attributable_fraction' during setup.
2026-07-23 09:52:50.923 | INFO     | simulation_4-results_context:131 - The following stratifications are registered but not used by any observers:
['ferritin_screening_coverage', 'hemoglobin_screening_coverage', 'sex']
2026-07-23 09:52:53.483 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-01 00:00:00
2026-07-23 09:53:07.141 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-02 00:00:00
2026-07-23 09:53:08.202 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-03 00:00:00
2026-07-23 09:53:09.733 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-04 00:00:00
2026-07-23 09:53:24.549 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-05 00:00:00
2026-07-23 09:53:41.142 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-06 00:00:00
2026-07-23 09:53:41.850 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-07 00:00:00
2026-07-23 09:53:42.561 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-08 00:00:00
2026-07-23 09:53:43.226 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-09 00:00:00
2026-07-23 09:53:43.979 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-10 00:00:00
2026-07-23 09:53:44.645 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-11 00:00:00
2026-07-23 09:53:45.358 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-12 00:00:00
2026-07-23 09:53:46.029 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-13 00:00:00
2026-07-23 09:53:46.691 | WARNING  | simulation_4-population_manager:747 - The 'maternal_obstructed_labor_and_uterine_rupture.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'maternal_obstructed_labor_and_uterine_rupture.incidence_risk.paf'.
2026-07-23 09:53:46.728 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-14 00:00:00
2026-07-23 09:53:47.421 | WARNING  | simulation_4-population_manager:747 - The 'maternal_hemorrhage.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'maternal_hemorrhage.incidence_risk.paf'.
2026-07-23 09:53:47.541 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-15 00:00:00
2026-07-23 09:53:48.231 | WARNING  | simulation_4-population_manager:747 - The 'maternal_sepsis_and_other_maternal_infections.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'maternal_sepsis_and_other_maternal_infections.incidence_risk.paf'.
2026-07-23 09:53:48.982 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-16 00:00:00
2026-07-23 09:53:50.281 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-17 00:00:00
2026-07-23 09:53:51.627 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-18 00:00:00
2026-07-23 09:53:54.957 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-19 00:00:00
2026-07-23 09:53:56.274 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-20 00:00:00
2026-07-23 09:53:57.624 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-21 00:00:00
2026-07-23 09:54:17.759 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-22 00:00:00
2026-07-23 09:54:25.181 | INFO     | simulation_4 - vivarium.framework.engine:280 - 2025-01-23 00:00:00
2026-07-23 09:54:25.874 | WARNING  | simulation_4-population_manager:747 - The 'postpartum_depression.incidence_risk.paf' attribute pipeline returned a pd.Series with a different name 'value'. For the column being added to the population state table, we will use 'postpartum_depression.incidence_risk.paf'.

In [68]:
step_shifts["observed_diff"] = step_shifts["mean_hgb_sepsis"] - step_shifts["mean_hgb_no_sepsis"]
step_shifts

,step,mean_hgb_sepsis,mean_hgb_no_sepsis,observed_diff
0,residual_maternal_disorders,106.976969,120.502504,-13.525535
1,abortion_miscarriage_ectopic_pregnancy,106.976969,120.502504,-13.525535
2,mortality,106.976969,120.502504,-13.525535
3,early_postpartum,106.976969,120.502504,-13.525535
4,late_postpartum,106.976969,120.502504,-13.525535
5,early_neonatal_mortality,93.729049,120.502504,-26.773456
6,late_neonatal_mortality,103.934626,120.502504,-16.567878
7,postpartum_depression,106.976969,120.502504,-13.525535

In [69]:
step_shifts = step_shifts.set_index("step")[["observed_diff"]].diff().iloc[1:]
#to_plot["target"]= 0
#to_plot.loc["early_neonatal_mortality", "target"] = sepsis_on_hemoglobin_shift["early_postpartum"]

step_shifts

                                        observed_diff
step
abortion_miscarriage_ectopic_pregnancy       0.000000
mortality                                    0.000000
early_postpartum                             0.000000
late_postpartum                              0.000000
early_neonatal_mortality                   -13.247920
late_neonatal_mortality                     10.205578
postpartum_depression                        3.042343

In [70]:
assert np.isclose(step_shifts.loc["early_neonatal_mortality"], sepsis_on_hemoglobin_shift["early_postpartum"])
# TODO change this to be correct step timing, include return to normal (?), and add late_postpartum

In [55]:
sim.get_population(PIPELINES.HEMOGLOBIN_EXPOSURE)  # we should be able to get this data at the end of the sim

IndexError: list index out of range