In [1]:
from vivarium import Artifact, InteractiveContext
import pandas as pd, numpy as np, os

In [2]:
! pip list | grep vivarium

# [software verion + commit hash . date]

vivarium                  3.5.5
vivarium_build_utils      2.0.11
vivarium_cluster_tools    2.1.21
vivarium_dependencies     1.0.1
vivarium_gates_mncnh      0.1.dev318+ga68a20600.d20251020 /mnt/share/homes/alibow/vivarium_gates_mncnh
vivarium_public_health    4.3.12
vivarium_testing_utils    0.2.5

In [3]:
! pip freeze | grep vivarium

vivarium==3.5.5
vivarium_build_utils==2.0.11
vivarium_cluster_tools==2.1.21
vivarium_dependencies==1.0.1
-e git+https://github.com/ihmeuw/vivarium_gates_mncnh.git@8ded26c7b55876890582ef86fce5ced298fcf775#egg=vivarium_gates_mncnh
vivarium_public_health==4.3.12
vivarium_testing_utils==0.2.5

In [4]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

from vivarium import InteractiveContext, Artifact

In [5]:
import vivarium_gates_mncnh
from vivarium.framework.configuration import build_model_specification
from pathlib import Path

path = Path(vivarium_gates_mncnh.__file__).parent / 'model_specifications/model_spec.yaml'
custom_model_specification = build_model_specification(path)
del custom_model_specification.configuration.observers
custom_model_specification.configuration.input_data.input_draw_number = 60
custom_model_specification.configuration.population.population_size = 20_000 #* 10

artifact_path = custom_model_specification.configuration.input_data.artifact_path
art = Artifact(artifact_path)

artifact_path

'/mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/model18.1/ethiopia.hdf'

In [6]:
draw_num = custom_model_specification.configuration.input_data.input_draw_number
draw = 'draw_' + str(draw_num)
draw

'draw_60'

In [7]:
sim = InteractiveContext(custom_model_specification)

get_event_name = sim._builder.time.simulation_event_name()
while get_event_name() != 'maternal_hemorrhage':
    sim.step()
# now one more step to advance past
sim.step()

baseline_pop = sim.get_population()
baseline_pop.head()

/ihme/code/alibow/miniconda/envs/vivarium_gates_mncnh_simulation/lib/python3.11/site-packages/vivarium_public_health/plugins/parser.py:19: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_filename

2025-10-28 13:31:13.892 | INFO     | simulation_1-artifact_manager:79 - Running simulation from artifact located at /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/model18.1/ethiopia.hdf.
2025-10-28 13:31:13.892 | INFO     | simulation_1-artifact_manager:80 - Artifact base filter terms are ['draw == 60'].
2025-10-28 13:31:13.893 | INFO     | simulation_1-artifact_manager:81 - Artifact additional filter terms are None.
2025-10-28 13:31:33.106 | WARNING  | simulation_1-results_manager:446 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']
2025-10-28 13:31:33.107 | WARNING  | simulation_1-results_manager:446 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']
2025-10-28 13:31:33.227 | INFO     | simulation_1-results_context:129 - The following stratifications are registered but not used by any observers:
['sex']
2025-10-28 13:31:35.829 | INFO     | simulation_1 - vivarium.framework.engine:284 - 2025-01-01 00:00:00
2025-10-28 13:31:37.955 | INFO     | simulation_1 - vivarium.framework.engine:284 - 2025-01-02 00:00:00
2025-10-28 13:31:38.432 | INFO     | simulation_1 - vivarium.framework.engine:284 - 2025-01-03 00:00:00
2025-10-28 13:31:38.959 | INFO     | simulation_1 - vivarium.framework.engine:284 - 2025-01-04 00:00:00
2025-10-28 13:31:39.430 | INFO     | simulation_1 - vivarium.framework.engine:284 - 2025-01-05 00:00:00
2025-10-28 13:31:39.971 | INFO     | simulation_1 - vivarium.framework.engine:284 - 2025-01-06 00:00:00
2025-10-28 13:31:40.446 | INFO     | simulation_1 - vivarium.framework.engine:284 - 2025-01-07 00:00:00
2025-10-28 13:31:40.938 | INFO     | simulation_1 - vivarium.framework.engine:284 - 2025-01-08 00:00:00
2025-10-28 13:31:41.426 | INFO     | simulation_1 - vivarium.framework.engine:284 - 2025-01-09 00:00:00
2025-10-28 13:31:41.917 | INFO     | simulation_1 - vivarium.framework.engine:284 - 2025-01-10 00:00:00

,tracked,alive,exit_time,location,age,sex,entrance_time,later_pregnancy_anc,anc_attendance,ultrasound_type,...,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_all_causes_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_all_causes_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_sepsis_and_other_neonatal_infections_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_sepsis_and_other_neonatal_infections_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_preterm_birth_with_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_preterm_birth_with_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_preterm_birth_without_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_preterm_birth_without_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_relative_risk
0,True,alive,NaT,Ethiopia,32.838854,Female,2024-12-31,False,first_trimester_only,standard,...,13.832881,12.367249,12.367249,13.832881,13.832881,12.367249,12.367249,13.832881,12.367249,13.832881
1,True,alive,NaT,Ethiopia,29.615904,Female,2024-12-31,True,later_pregnancy_only,standard,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2,True,alive,NaT,Ethiopia,31.716854,Female,2024-12-31,True,first_trimester_and_later_pregnancy,standard,...,1.007874,1.359047,1.359047,1.007874,1.007874,1.359047,1.359047,1.007874,1.359047,1.007874
3,True,alive,NaT,Ethiopia,31.383431,Female,2024-12-31,True,later_pregnancy_only,standard,...,1.008100,1.315407,1.315407,1.008100,1.008100,1.315407,1.315407,1.008100,1.315407,1.008100
4,True,alive,NaT,Ethiopia,21.400171,Female,2024-12-31,True,first_trimester_and_later_pregnancy,standard,...,1.155117,1.721376,1.721376,1.155117,1.155117,1.721376,1.721376,1.155117,1.721376,1.155117

In [8]:
custom_model_specification_mms = custom_model_specification#.copy()
custom_model_specification_mms.configuration.intervention.scenario = 'mms_total_scaleup'
mms_sim = InteractiveContext(custom_model_specification_mms)
get_mms_event_name = mms_sim._builder.time.simulation_event_name()
while get_mms_event_name() != 'maternal_hemorrhage':
    mms_sim.step()
# then one more
mms_sim.step()
mms_pop = mms_sim.get_population()
mms_pop.head()

2025-10-28 13:31:42.550 | INFO     | simulation_2-artifact_manager:79 - Running simulation from artifact located at /mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/model18.1/ethiopia.hdf.
2025-10-28 13:31:42.550 | INFO     | simulation_2-artifact_manager:80 - Artifact base filter terms are ['draw == 60'].
2025-10-28 13:31:42.551 | INFO     | simulation_2-artifact_manager:81 - Artifact additional filter terms are None.
2025-10-28 13:32:01.396 | WARNING  | simulation_2-results_manager:446 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']
2025-10-28 13:32:01.396 | WARNING  | simulation_2-results_manager:446 - Specified excluded stratifications are already not included by default: ['stillbirth', 'partial_term']
2025-10-28 13:32:01.514 | INFO     | simulation_2-results_context:129 - The following stratifications are registered but not used by any observers:
['sex']
2025-10-28 13:32:04.119 | INFO     | simulation_2 - vivarium.framework.engine:284 - 2025-01-01 00:00:00
2025-10-28 13:32:06.251 | INFO     | simulation_2 - vivarium.framework.engine:284 - 2025-01-02 00:00:00
2025-10-28 13:32:06.724 | INFO     | simulation_2 - vivarium.framework.engine:284 - 2025-01-03 00:00:00
2025-10-28 13:32:07.254 | INFO     | simulation_2 - vivarium.framework.engine:284 - 2025-01-04 00:00:00
2025-10-28 13:32:07.726 | INFO     | simulation_2 - vivarium.framework.engine:284 - 2025-01-05 00:00:00
2025-10-28 13:32:08.258 | INFO     | simulation_2 - vivarium.framework.engine:284 - 2025-01-06 00:00:00
2025-10-28 13:32:08.749 | INFO     | simulation_2 - vivarium.framework.engine:284 - 2025-01-07 00:00:00
2025-10-28 13:32:09.235 | INFO     | simulation_2 - vivarium.framework.engine:284 - 2025-01-08 00:00:00
2025-10-28 13:32:09.726 | INFO     | simulation_2 - vivarium.framework.engine:284 - 2025-01-09 00:00:00
2025-10-28 13:32:10.211 | INFO     | simulation_2 - vivarium.framework.engine:284 - 2025-01-10 00:00:00

,tracked,alive,exit_time,location,age,sex,entrance_time,later_pregnancy_anc,anc_attendance,ultrasound_type,...,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_all_causes_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_all_causes_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_sepsis_and_other_neonatal_infections_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_sepsis_and_other_neonatal_infections_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_preterm_birth_with_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_preterm_birth_with_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_preterm_birth_without_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_preterm_birth_without_rds_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_late_neonatal_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_relative_risk,effect_of_low_birth_weight_and_short_gestation_on_early_neonatal_neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma_relative_risk
0,True,alive,NaT,Ethiopia,32.838854,Female,2024-12-31,False,first_trimester_only,standard,...,13.832881,12.367249,12.367249,13.832881,13.832881,12.367249,12.367249,13.832881,12.367249,13.832881
1,True,alive,NaT,Ethiopia,29.615904,Female,2024-12-31,True,later_pregnancy_only,standard,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2,True,alive,NaT,Ethiopia,31.716854,Female,2024-12-31,True,first_trimester_and_later_pregnancy,standard,...,1.007874,1.359047,1.359047,1.007874,1.007874,1.359047,1.359047,1.007874,1.359047,1.007874
3,True,alive,NaT,Ethiopia,31.383431,Female,2024-12-31,True,later_pregnancy_only,standard,...,1.008100,1.315407,1.315407,1.008100,1.008100,1.315407,1.315407,1.008100,1.315407,1.008100
4,True,alive,NaT,Ethiopia,21.400171,Female,2024-12-31,True,first_trimester_and_later_pregnancy,standard,...,1.155117,1.721376,1.721376,1.155117,1.155117,1.721376,1.721376,1.155117,1.721376,1.155117

In [9]:
cols = ['anc_attendance',
       'oral_iron_intervention',
        'age',
        'hemoglobin_exposure',
        'maternal_hemorrhage',
        'pregnancy_outcome',
        'gestational_age_exposure'
       ]

In [10]:
pipelines = ['maternal_hemorrhage.incidence_risk',
             'maternal_hemorrhage.incidence_risk.paf',
             'hemoglobin_on_maternal_hemorrhage.relative_risk',
             'hemoglobin.exposure',
        'gestational_age.birth_exposure']

In [11]:
baseline_df = pd.concat([baseline_pop[cols],
                         pd.concat([sim.get_value(pipeline)(baseline_pop.index).rename(pipeline) for pipeline in pipelines], axis=1)], axis=1)
mms_df = pd.concat([mms_pop[cols],
                         pd.concat([mms_sim.get_value(pipeline)(mms_pop.index).rename(pipeline) for pipeline in pipelines], axis=1)], axis=1)
comp_df = baseline_df.merge(mms_df, right_index=True, left_index=True, suffixes=['_baseline','_mms'])
comp_df.head()

,anc_attendance_baseline,oral_iron_intervention_baseline,age_baseline,hemoglobin_exposure_baseline,maternal_hemorrhage_baseline,pregnancy_outcome_baseline,gestational_age_exposure_baseline,maternal_hemorrhage.incidence_risk_baseline,maternal_hemorrhage.incidence_risk.paf_baseline,hemoglobin_on_maternal_hemorrhage.relative_risk_baseline,...,age_mms,hemoglobin_exposure_mms,maternal_hemorrhage_mms,pregnancy_outcome_mms,gestational_age_exposure_mms,maternal_hemorrhage.incidence_risk_mms,maternal_hemorrhage.incidence_risk.paf_mms,hemoglobin_on_maternal_hemorrhage.relative_risk_mms,hemoglobin.exposure_mms,gestational_age.birth_exposure_mms
0,first_trimester_only,no_treatment,32.838854,101.743365,False,partial_term,39.939004,0.177863,0.086577,1.468884,...,32.838854,101.743365,False,partial_term,39.939004,0.177863,0.086577,1.468884,107.170580,40.481469
1,later_pregnancy_only,ifa,29.615904,108.277843,False,live_birth,41.254868,0.133469,0.084426,1.195394,...,29.615904,108.277843,False,live_birth,41.254868,0.133469,0.084426,1.195394,113.705058,41.006332
2,first_trimester_and_later_pregnancy,ifa,31.716854,136.486500,False,live_birth,38.263222,0.112873,0.086577,0.932165,...,31.716854,136.486500,False,live_birth,38.263222,0.112873,0.086577,0.932165,141.913715,40.191518
3,later_pregnancy_only,no_treatment,31.383431,125.773744,False,live_birth,38.459623,0.118078,0.086577,0.975150,...,31.383431,125.773744,False,live_birth,38.459623,0.118078,0.086577,0.975150,131.200958,40.142998
4,first_trimester_and_later_pregnancy,ifa,21.400171,106.899858,True,live_birth,39.232243,0.164750,0.066234,1.243336,...,21.400171,106.899858,True,live_birth,39.232243,0.164750,0.066234,1.243336,112.327073,39.032455

In [12]:
comp_df.loc[(comp_df.age_baseline < 30)
    &(comp_df.age_baseline > 25)][[x for x in comp_df.columns if 'paf' in x]]
# ok so the PAF values are the same across scenarios
# (PAF values vary by age group so I filtered to single age group to make sure PAFs did not vary by individual)

,maternal_hemorrhage.incidence_risk.paf_baseline,maternal_hemorrhage.incidence_risk.paf_mms
1,0.084426,0.084426
8,0.084426,0.084426
18,0.084426,0.084426
20,0.084426,0.084426
26,0.084426,0.084426
...,...,...
19970,0.084426,0.084426
19971,0.084426,0.084426
19980,0.084426,0.084426
19986,0.084426,0.084426
19990,0.084426,0.084426

In [13]:
comp_df[['maternal_hemorrhage_baseline','maternal_hemorrhage_mms']].value_counts() # so no one changed between scenarios

maternal_hemorrhage_baseline  maternal_hemorrhage_mms
False                         False                      17835
True                          True                        2165
Name: count, dtype: int64

In [14]:
comp_df[['maternal_hemorrhage.incidence_risk_baseline','maternal_hemorrhage.incidence_risk_mms']].describe()
# these are the same...

,maternal_hemorrhage.incidence_risk_baseline,maternal_hemorrhage.incidence_risk_mms
count,20000.000000,20000.000000
mean,0.171513,0.171513
std,0.096708,0.096708
min,0.066488,0.066488
25%,0.120641,0.120641
50%,0.135255,0.135255
75%,0.175165,0.175165
max,0.997958,0.997958

In [15]:
comp_df[['hemoglobin_on_maternal_hemorrhage.relative_risk_baseline','hemoglobin_on_maternal_hemorrhage.relative_risk_mms']].describe()
# so are these

,hemoglobin_on_maternal_hemorrhage.relative_risk_baseline,hemoglobin_on_maternal_hemorrhage.relative_risk_mms
count,20000.000000,20000.000000
mean,1.309378,1.309378
std,0.717638,0.717638
min,0.928561,0.928561
25%,0.952547,0.952547
50%,0.995722,0.995722
75%,1.293065,1.293065
max,5.530147,5.530147

In [16]:
comp_df[['hemoglobin_exposure_baseline','hemoglobin_exposure_mms']].describe()

# state table exposures do not change
# I think these are what is being used to assess hemorrhage risk

       hemoglobin_exposure_baseline  hemoglobin_exposure_mms
count                  20000.000000             20000.000000
mean                     119.296527               119.296527
std                       22.520905                22.520905
min                        5.855809                 5.855809
25%                      105.606440               105.606440
50%                      121.004421               121.004421
75%                      134.692074               134.692074
max                      197.627496               197.627496

In [17]:
comp_df[['hemoglobin.exposure_baseline','hemoglobin.exposure_mms']].describe()
# pipeline values do change between scenarios

       hemoglobin.exposure_baseline  hemoglobin.exposure_mms
count                  20000.000000             20000.000000
mean                     118.626996               121.001894
std                       23.019535                22.982363
min                        1.360743                 1.360743
25%                      104.599730               106.798376
50%                      120.345095               122.674579
75%                      134.370625               136.666348
max                      203.054711               203.054711

In [18]:
(comp_df['hemoglobin_exposure_baseline'].round(3) == comp_df['hemoglobin.exposure_baseline'].round(3)).value_counts(normalize=True)

False    1.0
Name: proportion, dtype: float64

In [19]:
comp_df[['hemoglobin_exposure_baseline','hemoglobin.exposure_baseline']]

       hemoglobin_exposure_baseline  hemoglobin.exposure_baseline
0                        101.743365                     97.248299
1                        108.277843                    113.705058
2                        136.486500                    141.913715
3                        125.773744                    121.278678
4                        106.899858                    112.327073
...                             ...                           ...
19995                    111.569358                    107.074291
19996                    113.218573                    108.723507
19997                    133.987621                    139.414835
19998                    144.518709                    140.023643
19999                    138.208893                    143.636108

[20000 rows x 2 columns]

In [20]:
gas = comp_df.groupby(['oral_iron_intervention_baseline','oral_iron_intervention_mms'])[['gestational_age.birth_exposure_baseline','gestational_age.birth_exposure_mms']].describe()
gas

                                                           gestational_age.birth_exposure_baseline  \
                                                                                             count
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                                                         7711.0
no_treatment                    mms                                                         4787.0
                                no_treatment                                                7502.0

                                                                       \
                                                                 mean
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         38.318404
no_treatment                    mms                         38.187590
                                no_treatment                37.642396

                                                                      \
                                                                 std
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         2.289932
no_treatment                    mms                         2.143847
                                no_treatment                2.684287

                                                                       \
                                                                  min
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                          7.961996
no_treatment                    mms                         18.567307
                                no_treatment                 0.963424

                                                                       \
                                                                  25%
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         37.522935
no_treatment                    mms                         37.398329
                                no_treatment                37.077336

                                                                       \
                                                                  50%
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         38.563998
no_treatment                    mms                         38.360294
                                no_treatment                37.983116

                                                                       \
                                                                  75%
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         39.629734
no_treatment                    mms                         39.447602
                                no_treatment                39.219750

                                                                       \
                                                                  max
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         42.084032
no_treatment                    mms                         41.928720
                                no_treatment                41.928474

                                                           gestational_age.birth_exposure_mms  \
                                                                                        count
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                                                    7711.0
no_treatment                    mms                                                    4787.0
                                no_treatment                                           7502.0

                                                                       \
                                                                 mean
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         38.669727
no_treatment                    mms                         38.695238
                                no_treatment                37.642396

                                                                      \
                                                                 std
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         2.278662
no_treatment                    mms                         2.133996
                                no_treatment                2.684287

                                                                       \
                                                                  min
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                          8.432429
no_treatment                    mms                         19.194455
                                no_treatment                 0.963424

                                                                       \
                                                                  25%
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         37.871265
no_treatment                    mms                         37.903375
                                no_treatment                37.077336

                                                                       \
                                                                  50%
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         38.912329
no_treatment                    mms                         38.865340
                                no_treatment                37.983116

                                                                       \
                                                                  75%
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         39.978065
no_treatment                    mms                         39.952647
                                no_treatment                39.219750


                                                                  max
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         42.432363
no_treatment                    mms                         42.433765
                                no_treatment                41.928474

In [21]:
ga_state_table = comp_df.groupby(['oral_iron_intervention_baseline','oral_iron_intervention_mms'])[['gestational_age_exposure_baseline','gestational_age_exposure_mms']].describe()
ga_state_table

                                                           gestational_age_exposure_baseline  \
                                                                                       count
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                                                   7711.0
no_treatment                    mms                                                   4787.0
                                no_treatment                                          7502.0

                                                                       \
                                                                 mean
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         38.158587
no_treatment                    mms                         38.188982
                                no_treatment                37.654386

                                                                      \
                                                                 std
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         2.319170
no_treatment                    mms                         2.186767
                                no_treatment                2.650424

                                                                       \
                                                                  min
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                          1.883920
no_treatment                    mms                         10.763665
                                no_treatment                 0.013854

                                                                       \
                                                                  25%
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         37.380562
no_treatment                    mms                         37.363731
                                no_treatment                37.081923

                                                                       \
                                                                  50%
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         38.403168
no_treatment                    mms                         38.382355
                                no_treatment                37.982919

                                                                       \
                                                                  75%
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         39.473020
no_treatment                    mms                         39.467608
                                no_treatment                39.238788

                                                                       \
                                                                  max
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         41.927735
no_treatment                    mms                         41.926277
                                no_treatment                41.927648

                                                           gestational_age_exposure_mms  \
                                                                                  count
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                                              7711.0
no_treatment                    mms                                              4787.0
                                no_treatment                                     7502.0

                                                                       \
                                                                 mean
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         38.158587
no_treatment                    mms                         38.188982
                                no_treatment                37.654386

                                                                      \
                                                                 std
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         2.319170
no_treatment                    mms                         2.186767
                                no_treatment                2.650424

                                                                       \
                                                                  min
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                          1.883920
no_treatment                    mms                         10.763665
                                no_treatment                 0.013854

                                                                       \
                                                                  25%
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         37.380562
no_treatment                    mms                         37.363731
                                no_treatment                37.081923

                                                                       \
                                                                  50%
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         38.403168
no_treatment                    mms                         38.382355
                                no_treatment                37.982919

                                                                       \
                                                                  75%
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         39.473020
no_treatment                    mms                         39.467608
                                no_treatment                39.238788


                                                                  max
oral_iron_intervention_baseline oral_iron_intervention_mms
ifa                             mms                         41.927735
no_treatment                    mms                         41.926277
                                no_treatment                41.927648

In [22]:
gas['gestational_age.birth_exposure_mms','mean'] - gas['gestational_age.birth_exposure_baseline','mean']

oral_iron_intervention_baseline  oral_iron_intervention_mms
ifa                              mms                           0.351323
no_treatment                     mms                           0.507647
                                 no_treatment                  0.000000
dtype: float64

In [23]:
ga_state_table['gestational_age_exposure_mms','mean'] - ga_state_table['gestational_age_exposure_baseline','mean']

oral_iron_intervention_baseline  oral_iron_intervention_mms
ifa                              mms                           0.0
no_treatment                     mms                           0.0
                                 no_treatment                  0.0
dtype: float64

In [24]:
art.load('risk_factor.multiple_micronutrient_supplementation.excess_gestational_age_shift_subpop_1')[draw].values[1]

0.4704324929524219

In [25]:
mms_ga_shift = art.load('risk_factor.multiple_micronutrient_supplementation.excess_gestational_age_shift_subpop_2')[draw].values[1]
mms_ga_shift

# note, observed shift will be expected to be slightly greater than this shift
# this shift applies to population with GA>32 weeks, which is vast majority of the population
# but a larger shift is applied to those with GA<32 weeks, so population-level shift will be greater

0.3483307282354286

In [26]:
ifa_ga_shift = art.load('risk_factor.iron_folic_acid_supplementation.excess_shift')[draw].values
ifa_ga_shift = ifa_ga_shift[len(ifa_ga_shift) - 1]
ifa_ga_shift

0.1567149325519542

In [27]:
mms_ga_shift + ifa_ga_shift

# so shifts match expectations in the pipeline values... no change in state table values

0.5050456607873828

In [28]:
comp_df['preterm_baseline'] = comp_df['gestational_age.birth_exposure_baseline'] < 37
comp_df['preterm_mms'] = comp_df['gestational_age.birth_exposure_mms'] < 37

In [29]:
comp_df[['preterm_baseline','preterm_mms']].value_counts()

preterm_baseline  preterm_mms
False             False          16525
True              True            3248
                  False            227
Name: count, dtype: int64

In [30]:
preterm_none = len(comp_df.loc[(comp_df.oral_iron_intervention_baseline=='no_treatment')
    &(comp_df.preterm_baseline)
    &(comp_df.anc_attendance_baseline!='none')]) / len(comp_df.loc[(comp_df.oral_iron_intervention_baseline=='no_treatment')
    &(comp_df.anc_attendance_baseline!='none')])
preterm_none

0.14706496762063923

In [31]:
preterm_ifa = len(comp_df.loc[(comp_df.oral_iron_intervention_baseline=='ifa')
    &(comp_df.preterm_baseline)]) / len(comp_df.loc[comp_df.oral_iron_intervention_baseline=='ifa'])
preterm_ifa

0.13292698742056802

In [32]:
preterm_mms = len(comp_df.loc[(comp_df.oral_iron_intervention_mms=='mms')
    &(comp_df.preterm_mms)]) / len(comp_df.loc[comp_df.oral_iron_intervention_mms=='mms'])
preterm_mms

0.12017922867658826

In [33]:
rr_ifa = preterm_ifa / preterm_none
rr_ifa # matches expectation

0.9038657511111635

In [34]:
rr_mms = preterm_mms / preterm_ifa
rr_mms # matches expectation

0.9040995437318752

In [35]:
sb_none = len(comp_df.loc[(comp_df.oral_iron_intervention_baseline=='no_treatment')
    &(comp_df.pregnancy_outcome_baseline=='stillbirth')
    &(comp_df.anc_attendance_baseline!='none')]) / len(comp_df.loc[(comp_df.oral_iron_intervention_baseline=='no_treatment')
    &(comp_df.anc_attendance_baseline!='none')
    &(comp_df.pregnancy_outcome_baseline.isin(['stillbirth','live_birth']))])
sb_none

0.01813752030319437

In [36]:
sb_ifa = len(comp_df.loc[(comp_df.oral_iron_intervention_baseline=='ifa')
    &(comp_df.pregnancy_outcome_baseline=='stillbirth')
    &(comp_df.anc_attendance_baseline!='none')]) / len(comp_df.loc[(comp_df.oral_iron_intervention_baseline=='ifa')
    &(comp_df.anc_attendance_baseline!='none')
    &(comp_df.pregnancy_outcome_baseline.isin(['stillbirth','live_birth']))])
sb_ifa

0.016421195192144914

In [37]:
sb_mms = len(comp_df.loc[(comp_df.oral_iron_intervention_mms=='mms')
    &(comp_df.pregnancy_outcome_mms=='stillbirth')
    &(comp_df.anc_attendance_mms!='none')]) / len(comp_df.loc[(comp_df.oral_iron_intervention_mms=='mms')
    &(comp_df.anc_attendance_mms!='none')
    &(comp_df.pregnancy_outcome_mms.isin(['stillbirth','live_birth']))])
sb_mms

0.017081554004791166

In [38]:
sb_baseline = len(comp_df.loc[#(comp_df.oral_iron_intervention_baseline=='ifa')
    (comp_df.pregnancy_outcome_baseline=='stillbirth')
    &(comp_df.anc_attendance_baseline!='none')]) / len(comp_df.loc[#(comp_df.oral_iron_intervention_baseline=='ifa')
    (comp_df.anc_attendance_baseline!='none')
    &(comp_df.pregnancy_outcome_baseline.isin(['stillbirth','live_birth']))])
sb_baseline

0.017081554004791166

In [39]:
sb_mms / sb_baseline

# no change when we look at comparison with common random numbers

1.0