# V&V neonatal outcomes

## Setup

In [21]:
import pandas as pd, numpy as np, os
from pathlib import Path
from vivarium.artifact import Artifact
import db_queries
from get_draws.api import get_draws
import matplotlib.pyplot as plt

from vivarium_gbd_access import constants as gbd_constants
from ihme_cc_get_estimates import get_machinery_estimates

In [2]:
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)

In [3]:
from vivarium_gates_mncnh.constants.paths import MODEL_RESULTS_DIR

base_results_dir = Path("/mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/results/") / MODEL_RESULTS_DIR

In [4]:
locations = [p.stem.title() for p in base_results_dir.iterdir() if p.is_dir()]

results_dirs = {}
assert set([p.stem for p in base_results_dir.iterdir()]) == set([l.lower() for l in locations])
for location in locations:
    location_dir = base_results_dir / location.lower()
    timestamps = sorted(location_dir.iterdir())
    last_timestamp = timestamps[-1]
    if len(timestamps) > 1:
        print(f'Multiple timestamps: {timestamps}, using {last_timestamp}')
    results_dirs[location] = location_dir / last_timestamp / 'results'

location_ids = db_queries.get_ids('location')
location_ids = location_ids.loc[location_ids.location_name.str.lower().isin([x.lower() for x in results_dirs.keys()])]

results_dirs

{'Ethiopia': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/results/model38.4/ethiopia/2026_08_26_21_00_13/results'),
 'Pakistan': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/results/model38.4/pakistan/2026_08_26_21_00_49/results'),
 'Nigeria': PosixPath('/mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/results/model38.4/nigeria/2026_08_26_21_00_40/results')}

In [5]:
def read_results(data, baseline_only=True, aggregate_seeds=True):
    df = pd.DataFrame()
    for location, result_dir in results_dirs.items():
        temp = pd.read_parquet(result_dir / data).drop(columns=['measure','entity','entity_type','sub_entity'])
        temp['location'] = location.lower()
        if 'scenario' not in temp.columns:
            temp['scenario'] = 'baseline'
        # FIXME: Make this work, generally merge with read_results in other V&V notebooks
        #temp['model_version'] = result.split('/')[8]
        if baseline_only:
            temp = temp.loc[temp.scenario == 'baseline']
        if 'random_seed' in temp.columns and aggregate_seeds:
            temp = temp.groupby([c for c in temp.columns if c != 'random_seed' and c != 'value']).sum().reset_index().drop(columns='random_seed')
        df = pd.concat([df, temp],ignore_index=True)
    return df

In [6]:
pd.read_parquet(results_dirs['Ethiopia'] / 'neonatal_acmrisk_sum').query("scenario == 'baseline' and input_draw == 60 and random_seed == 5616").value.sum()

0.0

In [7]:
import yaml
def load_yaml_file(path):
    with open(path) as stream:
        return yaml.safe_load(stream)

In [8]:
artifact_paths = {
    location: load_yaml_file(result_dir.parent / 'model_specification.yaml')['configuration']['input_data']['artifact_path']
    for location, result_dir
    in results_dirs.items()
}
artifact_paths

{'Ethiopia': '/mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/model38.4/ethiopia.hdf',
 'Pakistan': '/mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/model38.4/pakistan.hdf',
 'Nigeria': '/mnt/team/simulation_science/pub/models/vivarium_gates_mncnh/artifacts/model38.4/nigeria.hdf'}

In [9]:
def load_location_data(location, key):
    art = Artifact(artifact_paths[location])
    art = art.load(key)
    art['location'] = location.lower()
    art = art.reset_index().set_index(['location'] + art.index.names)
    return art
    
def load_artifact_data(key):
    data = pd.concat([load_location_data(location, key) for location in locations])
    return data

## All-cause mortality risk (before sampling)

In [10]:
causes = [
    'neonatal_preterm_birth_with_rds',
    'neonatal_preterm_birth_without_rds',
    'neonatal_preterm_birth',
    'neonatal_sepsis_and_other_neonatal_infections',
    'neonatal_encephalopathy_due_to_birth_asphyxia_and_trauma',
    'other_causes',
]

In [11]:
# TODO: name variable
c = db_queries.get_ids('cause')
# FIXME: What is this doing? Is there a less confusing way to get what we need here?
c = c.loc[c.cause_name.str.lower().isin([x.replace('_',' ').lower() for x in causes]) | (c.cause_name.str.lower() == 'all causes')]
gbd_cause_ids = c.cause_id.unique()
c

,cause_id,cause_name,acause,cause_description
0,294,All causes,_all,None
87,381,Neonatal preterm birth,neonatal_preterm,None
88,382,Neonatal encephalopathy due to birth asphyxia ...,neonatal_enceph,None
89,383,Neonatal sepsis and other neonatal infections,neonatal_sepsis,None

In [12]:
# now load up matching GBD 2023 data
# TODO: Comment and make constants for these magic numbers (or get them from gbd_mapping or similar)

gbd_births = db_queries.get_population(location_id=[179,165,214],
                                release_id=16,
                                year_id=2023,
                                age_group_id=164,
                                sex_id=[1, 2])

In [ ]:
gbd_deaths = get_draws(
    entity="cause",
    entity_id=gbd_cause_ids,         
    #compare_version_id=8333,       # COMO v1773, release 33
    estimates="draws",
    location_id=[179,165,214],
    release_id=16,
    year_id=2023,
    #source='codcorrect',
    metric_id=1,
    measure_id=1,
    #gbd_id=gbd_cause_ids,
    age_group_id=[2,3], # enn and lnn
    #gbd_id_type='cause_id'
    sex_id=gbd_constants.SEX.MALE + gbd_constants.SEX.FEMALE
)

In [40]:
gbd_deaths = get_draws(location_id=[179,165,214],
                                release_id=16,
                                year_id=2023,
                                source='codcorrect',
                                metric_id=1,
                                measure_id=1,
                                gbd_id=gbd_cause_ids,
                                age_group_id=[2,3], # enn and lnn
                                gbd_id_type='cause_id')

/ihme/homes/tylerdy/miniforge3/envs/vivarium_gates_mncnh_artifact/lib/python3.11/site-packages/get_draws/api.py:194: UserWarning: No version_id was specified, so get_draws will automatically determine a best version ID to use from the given parameters. If you want to retrieve a specific version please pass a version_id directly.
  warnings.warn(

In [41]:
gbd_deaths.sort_index(axis=1)

,age_group_id,cause_id,draw_0,draw_1,draw_10,draw_100,draw_101,draw_102,draw_103,draw_104,...,draw_96,draw_97,draw_98,draw_99,location_id,measure_id,metric_id,sex_id,version_id,year_id
0,2,294,94085.214083,107131.800620,89525.321274,107730.031228,101639.011886,91460.800832,98903.714259,101615.358675,...,95226.590558,96084.943333,90304.264855,104939.765695,165,1,1,1,528,2023
1,2,381,27103.048005,24289.083992,27248.783864,27934.386348,48727.102591,31682.924971,23706.194678,36825.213653,...,27580.313992,23711.494061,17372.237472,24125.706483,165,1,1,1,528,2023
2,2,382,43442.473229,55806.600301,34255.533974,63791.035660,30023.577805,37444.379321,53491.645916,37775.040636,...,51513.211084,49340.465507,51288.846125,51364.429825,165,1,1,1,528,2023
3,2,383,5445.305185,6445.570926,5934.639708,3473.888109,8309.421916,5772.666158,3555.655183,11391.849666,...,5774.001557,4535.312028,9725.207918,9090.178107,165,1,1,1,528,2023
4,3,294,14298.854965,17651.951594,22617.600805,14224.213962,18209.053406,15341.609238,17760.556934,15137.951377,...,17634.011333,13929.655164,11068.389141,16196.055499,165,1,1,1,528,2023
5,3,381,3268.516906,2980.631983,4290.054084,3449.797512,6616.522133,3442.503259,2811.972840,3990.166654,...,4483.060049,2755.651538,1535.615522,2503.678349,165,1,1,1,528,2023
6,3,382,3171.781456,4815.995972,3400.779112,5113.031601,2288.124586,4114.612820,5307.080086,2427.539196,...,5508.903248,3414.551947,2974.804510,3573.185604,165,1,1,1,528,2023
7,3,383,1888.933917,2339.259107,2999.453144,1255.312316,3146.570800,1986.116347,1274.460134,3463.611157,...,2869.485536,1621.387379,2552.979487,2954.818025,165,1,1,1,528,2023
8,2,294,50257.816711,51051.263832,53340.322257,50916.589816,48834.202556,49644.870552,48064.621139,49402.983427,...,50865.978363,50247.977804,46943.040826,52877.942684,179,1,1,1,528,2023
9,2,381,13439.742978,10544.799803,11603.565316,11663.354801,14948.233813,12855.662295,9417.778208,11339.004242,...,13151.158496,13235.202706,10615.671865,14641.614610,179,1,1,1,528,2023
10,2,382,19719.964396,19217.336450,19865.302349,22402.368125,19290.836702,16224.411375,22365.614000,18759.717763,...,23547.379770,17511.273656,17931.387338,15551.841850,179,1,1,1,528,2023
11,2,383,3147.760958,4002.044488,3329.444498,6252.815126,3970.898311,6206.312501,2831.018220,4087.965233,...,4216.620375,2061.330936,7623.652972,4679.888658,179,1,1,1,528,2023
12,3,294,12125.441974,13999.657770,11783.315381,13768.609732,12973.676751,13989.824626,14208.642010,12857.381750,...,12215.054451,14412.539166,12284.687394,13334.273810,179,1,1,1,528,2023
13,3,381,2239.297884,1755.125828,1771.628302,2279.013352,3179.151367,1724.970309,1416.611902,2064.645050,...,2145.645117,2360.836196,1457.531046,1778.136718,179,1,1,1,528,2023
14,3,382,1703.811672,1518.850715,1170.105461,2135.503186,1381.809017,1095.305333,1634.117075,1510.671852,...,2453.950314,1863.494129,1398.348235,1109.989904,179,1,1,1,528,2023
15,3,383,2453.097129,2881.680968,2145.140379,4472.386931,3263.199985,4291.410288,2414.138508,3222.615928,...,3379.424670,2039.015335,4493.231588,3342.484401,179,1,1,1,528,2023
16,2,294,25141.561213,26193.539247,28342.469650,26612.497245,27976.561934,25848.372563,24401.372087,24255.832923,...,26210.780753,26447.065025,25993.597895,24963.659080,179,1,1,2,528,2023
17,2,381,5695.621725,6413.242309,5868.027025,5239.220083,6626.881488,4503.302141,4122.444509,5274.884727,...,6674.708620,5380.908708,8554.032034,5859.795624,179,1,1,2,528,2023
18,2,382,7870.894554,7702.503329,8222.745475,8632.449698,7969.076928,13114.833066,8816.320773,9309.621119,...,7563.570770,8585.364684,6822.464197,8553.510173,179,1,1,2,528,2023
19,2,383,2101.701094,2523.086327,2357.361650,1757.600294,1442.086874,944.828413,1331.243814,2467.190582,...,1829.990070,2667.465436,1404.180354,2148.816559,179,1,1,2,528,2023
20,3,294,7880.722093,7310.890126,7874.377451,7192.094429,7721.921836,7354.915560,8583.524544,7944.706730,...,7753.479404,7358.236351,7013.560244,8235.689007,179,1,1,2,528,2023
21,3,381,742.178054,803.724568,899.846229,693.753909,729.246260,1025.187524,662.620847,773.302795,...,906.620876,597.521375,1182.377002,911.221319,179,1,1,2,528,2023
22,3,382,795.638002,608.518001,514.921259,728.482158,754.516044,1206.457669,738.263258,891.577582,...,815.538129,500.591213,607.504657,758.950917,179,1,1,2,528,2023
23,3,383,1845.871125,1709.343763,1501.639763,1182.856869,1138.192717,1064.715815,1217.789572,1864.598868,...,1559.362690,1520.570353,1214.326599,1705.656303,179,1,1,2,528,2023
24,2,294,114040.828476,116522.046038,115865.501586,105958.469688,113668.020109,113343.730000,121601.328044,124519.107665,...,127918.577638,120887.864510,116839.170897,119823.963347,214,1,1,1,528,2023
25,2,381,28305.412626,26915.673942,28891.767626,23190.674073,47179.696881,24249.245750,24201.574887,40914.009074,...,28581.856894,28303.171560,15154.258052,21370.485878,214,1,1,1,528,2023
26,2,382,39031.849706,42256.750519,29574.886632,57359.520298,30535.616096,40313.147751,51928.340501,39305.806472,...,69414.201647,49072.402046,51226.747217,45626.141175,214,1,1,1,528,2023
27,2,383,5195.555634,8671.463964,6226.453212,7286.180042,8284.739040,12245.096356,5768.087636,10149.302080,...,7296.733941,4590.404104,19880.911220,12124.862324,214,1,1,1,528,2023
28,3,294,22270.771728,23504.019884,21135.917123,24290.317486,22384.251487,23571.381050,23553.965034,23442.427468,...,25024.896738,22845.349345,21032.688331,24574.379386,214,1,1,1,528,2023
29,3,381,3309.867617,2548.974011,2264.122884,3388.492913,4828.628877,1940.061975,2064.715732,4451.852415,...,4284.069062,3232.724647,965.338813,1989.914803,214,1,1,1,528,2023
30,3,382,2229.162392,2050.280146,1058.909781,4573.555973,1447.235680,1706.293910,2305.605628,1995.797359,...,5012.279107,2842.289971,1702.321616,2130.256867,214,1,1,1,528,2023
31,3,383,3602.958878,4798.125692,3012.754531,6437.197404,4786.045760,6204.661000,2900.328431,5742.051047,...,6514.636973,3351.102098,7111.095971,7191.128224,214,1,1,1,528,2023
32,2,294,67159.099574,58037.924519,47677.214414,61520.664976,64772.472440,64944.966323,45275.470680,58337.562010,...,73198.705536,59103.258009,65899.476110,54395.128265,165,1,1,2,528,2023
33,2,381,16804.932208,13504.975152,14908.251553,18800.772284,18015.933281,24737.804788,13288.039287,15421.031970,...,18062.981064,15479.842385,26332.986364,17721.774583,165,1,1,2,528,2023
34,2,382,35594.558321,32032.045666,21517.660428,29924.043863,32411.696967,29385.668305,21905.052019,30940.871610,...,38177.996551,27195.240690,27789.677385,25170.088176,165,1,1,2,528,2023
35,2,383,4194.458101,3938.383520,3155.602307,1507.209560,2600.068903,1722.748230,1688.344994,4088.521902,...,4362.561961,5775.800820,1941.550848,3831.209684,165,1,1,2,528,2023
36,3,294,17949.043136,16209.479546,14965.963785,16122.137914,13251.117794,18165.419272,18958.011635,22638.697853,...,21587.515915,15624.840608,16989.058335,22421.469913,165,1,1,2,528,2023
37,3,381,4757.828263,3947.150307,5044.364291,5216.581711,3791.857519,6704.577568,5013.623730,6659.628711,...,5536.341434,3976.326705,7027.010204,7876.502456,165,1,1,2,528,2023
38,3,382,5915.284462,5157.196264,3688.625364,4608.771582,3627.918356,4579.611131,5863.513570,6750.380496,...,6081.609821,3772.023847,3523.558539,5571.463664,165,1,1,2,528,2023
39,3,383,1516.476165,1547.651095,1271.932032,532.997037,759.295501,733.186266,824.701364,2143.120399,...,1827.776642,1944.293578,638.422005,2237.703657,165,1,1,2,528,2023
40,2,294,86448.611595,77395.928016,78695.725833,81758.013860,80736.304783,77457.756190,80699.713990,83169.594497,...,83502.441136,76656.519316,84276.743507,78180.074566,214,1,1,2,528,2023
41,2,381,15667.659621,14753.913527,20139.466047,19415.465489,18497.777876,19587.062866,18681.036892,18068.308127,...,13571.731595,15443.144263,29442.193101,21246.486129,214,1,1,2,528,2023
42,2,382,43860.020233,36799.585550,26027.369014,34764.539822,32398.153388,36553.859698,31895.313607,35450.381282,...,39402.193682,27804.235444,28234.135973,32105.200190,214,1,1,2,528,2023
43,2,383,4902.904389,5685.309264,7748.389691,4718.174485,5264.339555,3500.583315,6175.972488,8574.274548,...,5224.100273,8828.930706,5166.494417,5567.863190,214,1,1,2,528,2023
44,3,294,19575.656179,18776.434095,18311.718801,17425.362951,20030.489625,18989.505997,20227.337947,20548.574111,...,18405.662499,20973.966133,20470.257578,19296.241373,214,1,1,2,528,2023
45,3,381,2522.145764,2189.575361,2395.566689,2737.166534,2597.438136,2962.479471,2318.651580,2077.010247,...,1808.971683,1917.271997,4468.525861,3033.259428,214,1,1,2,528,2023
46,3,382,3218.371498,2640.822549,1425.933418,2414.775340,2139.378678,2530.935318,2014.054684,1934.111240,...,2543.350614,1488.207333,1942.376074,2047.671954,214,1,1,2,528,2023
47,3,383,3613.528399,3745.463646,4057.548397,3159.925218,3485.771201,2630.568881,3463.211957,4677.149689,...,3323.071862,4856.931940,3675.209813,3529.869344,214,1,1,2,528,2023

In [ ]:
gbd_deaths_new = get_machinery_estimates(
    location_id=[179,165,214],
    release_id=16,
    year_id=2023,
    #source='codcorrect',
    metric_id=1,
    measure_id=1,
    age_group_id=[2,3], # enn and lnn
    #gbd_id=[383],
    #gbd_id_type='cause_id',
    entity='cause',
    entity_id=gbd_cause_ids,
    #source=gbd_constants.SOURCES.CODCORRECT,
    sex_id=gbd_constants.SEX.MALE + gbd_constants.SEX.FEMALE,
    estimates="draws",
).drop(columns='gbd_process_version_id')

In [65]:
assert np.allclose(gbd_deaths.sort_index(axis=1), gbd_deaths_new.sort_index(axis=1))

In [ ]:
def sim_summaries_from_moments(quantity, group_cols=['location', 'child_sex', 'child_age_group', 'input_draw']):
    count = read_results(f'{quantity}_count', baseline_only=True)
    count = count.set_index([c for c in count.columns if c != 'value'])
    sum = read_results(f'{quantity}_sum', baseline_only=True)
    sum = sum.set_index([c for c in sum.columns if c != 'value'])
    sum_of_squares = read_results(f'{quantity}_sum_of_squares', baseline_only=True)
    sum_of_squares = sum_of_squares.set_index([c for c in sum_of_squares.columns if c != 'value'])
    nonzero = count.value > 0
    count = count[nonzero]
    sum = sum[nonzero]
    sum_of_squares = sum_of_squares[nonzero]

    mean = (sum.groupby(group_cols).sum() / count.groupby(group_cols).sum()).value

    variance = (
        (
            sum_of_squares.groupby(group_cols).sum()
            /
            count.groupby(group_cols).sum()
        )
        -
        (
            (
                (sum.groupby(group_cols).sum() /
                count.groupby(group_cols).sum())
            ) ** 2
        )
    )
    std_error = (np.sqrt(variance) / np.sqrt(count[count.value > 0].groupby(group_cols).sum())).value.rename('std_error')
    return pd.DataFrame([mean, std_error]).T

In [ ]:
sim_acmrisk = sim_summaries_from_moments('neonatal_acmrisk')
sim_acmrisk

In [ ]:
draws = list(sim_acmrisk.index.get_level_values('input_draw').unique())
draws

In [ ]:
draw_cols = [f'draw_{c}' for c in draws]
draw_cols

In [ ]:
gbd_enn_0 = gbd_births.set_index(['location_id','sex_id'])[['population']]
gbd_enn_deaths = gbd_deaths.loc[gbd_deaths.age_group_id==2].set_index(['location_id','sex_id','cause_id'])[draw_cols].reset_index()
gbd_enn_mortality_ratio = gbd_enn_deaths.merge(gbd_enn_0, on=['location_id','sex_id'])
for col in draw_cols:
    gbd_enn_mortality_ratio[col] = gbd_enn_mortality_ratio[col] / gbd_enn_mortality_ratio.population
gbd_enn_mortality_ratio = gbd_enn_mortality_ratio.drop(columns='population').reset_index()
gbd_enn_mortality_ratio['child_age_group'] = 'early_neonatal'

gbd_lnn_0 = gbd_enn_deaths.loc[gbd_enn_deaths.cause_id==294].drop(columns='cause_id').merge(gbd_enn_0, on=['location_id','sex_id'])
for col in draw_cols:
    gbd_lnn_0[col] = gbd_lnn_0.population - gbd_lnn_0[col]
gbd_lnn_deaths = gbd_deaths.loc[gbd_deaths.age_group_id==3].set_index(['location_id','sex_id','cause_id'])[draw_cols].reset_index()
gbd_lnn_mortality_ratio = (gbd_lnn_deaths.set_index(['location_id','sex_id','cause_id']) 
                           / gbd_lnn_0.drop(columns='population').set_index(['location_id','sex_id'])).reset_index()
gbd_lnn_mortality_ratio['child_age_group'] = 'late_neonatal'

gbd_mortality_ratio = pd.concat([gbd_enn_mortality_ratio, gbd_lnn_mortality_ratio], ignore_index=True).drop(columns='index')
gbd_mortality_ratio = gbd_mortality_ratio.merge(db_queries.get_ids('location')[['location_id','location_name']], on='location_id').rename(columns={'location_name':'location'})
gbd_mortality_ratio['location'] = gbd_mortality_ratio.location.str.lower()
# TODO: Do we not get "both" sex numbers for the deaths?
gbd_mortality_ratio['child_sex'] = np.where(gbd_mortality_ratio.sex_id==1,'Male','Female')
gbd_mortality_ratio = gbd_mortality_ratio.sort_values(by=['location','child_age_group','child_sex']).reset_index().drop(columns=['index'])
# FIXME: Make this robust (not level_6 and 0)
gbd_mortality_ratio = (gbd_mortality_ratio.set_index([c for c in gbd_mortality_ratio.columns if 'draw' not in c]).stack().reset_index()
                       .rename(columns={'level_6':'draw',0:'gbd_value'}))
gbd_mortality_ratio['input_draw'] = gbd_mortality_ratio.draw.str.split('_',expand=True)[1].astype(int)
gbd_mortality_ratio = gbd_mortality_ratio.merge(db_queries.get_ids('cause')[['cause_name','cause_id']], on='cause_id')
gbd_mortality_ratio['cause_name'] = gbd_mortality_ratio['cause_name'].str.replace(' ','_').str.lower()
gbd_mortality_ratio = gbd_mortality_ratio.rename(columns={'cause_name':'cause'})

# now calculate "other causes" mortality ratio
gbd_all = gbd_mortality_ratio.loc[gbd_mortality_ratio.cause=='all_causes'].set_index(['location_id','sex_id','child_age_group','child_sex',
                                                                                      'location','draw','input_draw'])[['gbd_value']]
# TODO: Could just filter with `gbd_cause_ids`?
gbd_modeled = gbd_mortality_ratio.loc[gbd_mortality_ratio.cause!='all_causes'].groupby(['location_id','sex_id','child_age_group','child_sex',
                                                                                      'location','draw','input_draw'])[['gbd_value']].sum()
gbd_other = (gbd_all - gbd_modeled).reset_index()
gbd_other['cause'] = 'other_causes'
gbd_mortality_ratio = pd.concat([gbd_mortality_ratio, gbd_other], ignore_index=True)

# now split preterm birth mortality
gbd_preterm = (gbd_mortality_ratio.loc[gbd_mortality_ratio.cause=='neonatal_preterm_birth']
               .drop(columns='cause').set_index([x for x in gbd_mortality_ratio if x not in ['gbd_value','cause']]))
# TODO: Comment and make constants for these magic numbers/link to docs
# Does it really make sense to check this? Shouldn't we just check the RDS/no-RDS split?
gbd_preterm_rds = (gbd_preterm * 0.85).reset_index()
gbd_preterm_rds['cause'] = 'neonatal_preterm_birth_with_rds'
gbd_preterm_without_rds = (gbd_preterm * 0.15).reset_index()
gbd_preterm_without_rds['cause'] = 'neonatal_preterm_birth_without_rds'
gbd_mortality_ratio = pd.concat([gbd_mortality_ratio, gbd_preterm_rds, gbd_preterm_without_rds], ignore_index=True)

gbd_mortality_ratio

In [ ]:
documented_draws = [115, 60, 118, 197, 79, 244, 22, 167, 146, 71, 28, 156, 94, 170, 109, 26, 35, 114, 178, 127]
# obtained from: https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_mncnh_portfolio/concept_model.html#id20
# on 11/3/2025

In [ ]:
# check that all of the draws in simulation results are in the documented list
assert set(draws) <= set(documented_draws), f"Draws in simulation results but not documented draw list: {set(draws) - set(documented_draws)}"

In [ ]:
def plot_sim_vs_gbd(plot_data, title):
    plt.figure()
    # TODO: Use plt.subplots here
    # 2 rows, 1 column, open the first subplot, which we will use for plotting the values against each other directly
    plt.subplot(2,1,1)
    
    # This accumulator tracks which colors we have used
    # (indexes into the matplotlib cycle: https://matplotlib.org/stable/users/explain/colors/colors.html#cn-color-selection)
    color_id = 0

    for sex_str in ['Male', 'Female']:
        for age_group in ['early_neonatal', 'late_neonatal']:
            color = f'C{color_id}'
            # TODO: Better variable names
            zz = plot_data.loc[(plot_data.child_sex==sex_str) & (plot_data.child_age_group == age_group)]
            xx = zz.gbd_value.values
            yy = zz['value'].values
            plt.plot(xx, yy, 'o', label=f'{sex_str}, {age_group}',
                            mew=1, color='none', mec=color)
            plt.scatter(xx.mean(), yy.mean(), color=color, s=75)
            color_id += 1

    max_val = plot_data[['gbd_value', 'value']].max().max()
    plt.plot([0, max_val], [0, max_val], 'k--')
    plt.xlabel('GBD value')
    plt.ylabel('Sim value')
    plt.title(title)
    plt.grid()

    # Move to second subplot, where we will plot *relative* error
    # TODO: remove duplication
    plt.subplot(2,1,2)
    plot_data = plot_data.assign(ratio=lambda df: df['value'] / df['gbd_value'])
    color_id = 0

    for sex_str in ['Male', 'Female']:
        for age_group in ['early_neonatal', 'late_neonatal']:
            color = f'C{color_id}'
            zz = plot_data.loc[(plot_data.child_sex==sex_str) & (plot_data.child_age_group == age_group)]
            xx = zz.gbd_value.values
            yy = zz['ratio'].values
            plt.plot(xx, yy, 'o', label=f'{sex_str}, {age_group}',
                            mew=1, color='none', mec=color)
            plt.scatter(xx.mean(), yy.mean(), color=color, s=75)
            color_id += 1

    # Plot rough heuristic "tolerance" lines
    plt.axhline(1, color='k', linestyle='dashed')
    plt.axhline(.9, color='k', linestyle='dotted')
    plt.axhline(1.1, color='k', linestyle='dotted')

    plt.legend(loc=(1.01, .01))

    plt.xlabel('GBD value')
    plt.ylabel('Sim value / GBD value')
    plt.grid()

def plot_all_cause_mortality_risk(location):
    plot_data = sim_acmrisk.reset_index().merge(gbd_mortality_ratio[gbd_mortality_ratio.cause == 'all_causes'], on=['location','child_age_group','child_sex','input_draw'])
    plot_data = plot_data.loc[(plot_data.location==location.lower())]

    plot_sim_vs_gbd(
        plot_data,
        title=f'Age-specific all-cause mortality risk ({location.capitalize()})\n(probability of death in age group)'
    )

In [ ]:
for location in locations:
    plot_all_cause_mortality_risk(location)

## All-cause mortality ratio (after sampling)

In [ ]:
deaths = read_results('neonatal_burden_observer_disorder_deaths', baseline_only=True)
# collapse preterm birth causes of death
deaths_preterm = deaths.loc[deaths.neonatal_burden_observer_cause_of_death.str.contains('preterm')]
deaths_preterm['neonatal_burden_observer_cause_of_death'] = 'neonatal_preterm_birth'
deaths_preterm = deaths_preterm.groupby([x for x in deaths_preterm.columns if x != 'value']).sum().reset_index()
deaths_all = deaths.groupby([x for x in deaths.columns if x not in ['value','neonatal_burden_observer_cause_of_death']])['value'].sum().reset_index()
deaths_all['neonatal_burden_observer_cause_of_death'] = 'all_causes'
deaths = pd.concat([deaths, deaths_preterm, deaths_all], ignore_index=True)
births =  read_results('births', baseline_only=True).rename(columns={'sex':'child_sex'})
#pregnancies = read_results('anc', baseline_only=True)

In [ ]:
# check that there are no preterm birth deaths among non preterm babies if we have the stratification to do it

if 'preterm_birth' in deaths.columns:
    assert deaths.loc[(deaths.preterm_birth==False) 
                  & (deaths.neonatal_burden_observer_cause_of_death == 'neonatal_preterm_birth')].value.sum() == 0, "Preterm deaths among non-preterm babies"

In [ ]:
# get "alive" counts at the beginning of each age group

groupby_cols = ['location','child_sex','input_draw','scenario']
def calculate_sim_mortality_ratio(groupby_cols):
    sim_mortality_ratio = pd.DataFrame()

    enn0 = births.loc[births.pregnancy_outcome=='live_birth'].groupby(groupby_cols)['value'].sum()
    enn_deaths = deaths.loc[(deaths.child_age_group == 'early_neonatal')
                            &(deaths.neonatal_burden_observer_cause_of_death=='all_causes')].groupby(groupby_cols)['value'].sum()
    lnn_0 = enn0 - enn_deaths

    for cause in list(deaths.neonatal_burden_observer_cause_of_death.unique()):
        enn_deaths = deaths.loc[(deaths.child_age_group == 'early_neonatal')
                                &(deaths.neonatal_burden_observer_cause_of_death == cause)].groupby(groupby_cols)['value'].sum()
        lnn_deaths = deaths.loc[(deaths.child_age_group == 'late_neonatal')
                                &(deaths.neonatal_burden_observer_cause_of_death == cause)].groupby(groupby_cols)['value'].sum()
        enn_mortality_ratio = (enn_deaths / enn0).reset_index()
        enn_mortality_ratio['child_age_group'] = 'early_neonatal'
        lnn_mortality_ratio = (lnn_deaths / lnn_0).reset_index()
        lnn_mortality_ratio['child_age_group'] = 'late_neonatal'

        # TODO: Give this a more descriptive name than `temp`, likely by accumulating these in a list
        # and doing pd.concat once
        temp = pd.concat([enn_mortality_ratio, lnn_mortality_ratio], ignore_index=True)
        temp['cause'] = cause
        sim_mortality_ratio = pd.concat([sim_mortality_ratio, temp], ignore_index=True)
    return sim_mortality_ratio

In [ ]:
groupby_cols = ['location','child_sex','input_draw','scenario']
sim_mortality_ratio = calculate_sim_mortality_ratio(groupby_cols)
sim_mortality_ratio = sim_mortality_ratio.loc[sim_mortality_ratio.scenario == 'baseline']
sim_mortality_ratio.head()

In [ ]:
sim_mortality_ratio.cause.unique()

In [ ]:
acmrisk_artifact = load_artifact_data('cause.all_causes.all_cause_mortality_risk')[draw_cols]
acmrisk_artifact['cause'] = 'all_causes'
acmrisk_artifact['child_age_group'] = np.where(acmrisk_artifact.reset_index().age_start == 0, 'early_neonatal', 'later_neonatal')
# FIXME: use set_index(append=True)
acmrisk_artifact = acmrisk_artifact.reset_index().set_index(acmrisk_artifact.index.names + ['cause','child_age_group'])
acmrisk_artifact.head()

In [ ]:
# TODO: Give this variable a more descriptive name
plot = sim_mortality_ratio.merge(gbd_mortality_ratio, on=['location','child_age_group','child_sex','input_draw','cause'])
# FIXME: Make this robust (not level_8)
plot = plot.merge(acmrisk_artifact.stack().rename('value').reset_index().rename(columns={'level_8':'draw','sex':'child_sex','value':'artifact_value'}),
                 on=['child_sex','child_age_group','draw','cause','location'])
plot

In [ ]:
# TODO: Check this using pandas methods
assert np.all(np.unique(plot.gbd_value / plot.artifact_value) == [1.]), "GBD values do not match artifact values exactly"

In [ ]:
def plot_mortality_ratio(cause, location):
    # TODO: Give this a better name
    scalar=1000

    plot_data = sim_mortality_ratio.merge(gbd_mortality_ratio, on=['location','child_age_group','child_sex','input_draw','cause'])
    plot_data = plot_data.loc[(plot_data.location==location.lower()) & (plot_data.cause==cause)]
    plot_data['value'] = plot_data['value'] * scalar
    plot_data['gbd_value'] = plot_data['gbd_value'] * scalar

    plot_sim_vs_gbd(
        plot_data,
        title=f'Age-specific {cause} mortality ratio ({location.capitalize()})\n(deaths in age group per {scalar} starting population)'
    )

In [ ]:
for location in locations:
    plot_mortality_ratio('all_causes',location)

## Cause-specific mortality risk (before sampling)

In [ ]:
sim_csmrisk = pd.concat([
    sim_summaries_from_moments(f'neonatal_{cause}_csmrisk').assign(cause=cause).set_index('cause', append=True)
    for cause in causes
    if cause not in ['other_causes', 'neonatal_preterm_birth']
])
sim_csmrisk

In [ ]:
def plot_cause_specific_mortality_risk(cause, location):
    plot_data = sim_csmrisk.reset_index().merge(gbd_mortality_ratio, on=['location','child_age_group','child_sex','input_draw', 'cause'])
    plot_data = plot_data.loc[(plot_data.location==location.lower()) & (plot_data.cause==cause)]

    plot_sim_vs_gbd(
        plot_data,
        title=f'Age-specific {cause} mortality risk ({location.capitalize()})\n(probability of death in age group)'
    )

In [ ]:
for cause in causes:
    if cause in ['other_causes', 'neonatal_preterm_birth']:
        continue
    for location in locations:
        plot_cause_specific_mortality_risk(cause, location)

## Impossible cause-specific mortality risk

In [ ]:
sim_impossible_csmrisk = sim_summaries_from_moments('neonatal_impossible_csmrisk').sort_values('value')
sim_impossible_csmrisk

In [ ]:
sim_impossible_csmrisk.groupby(['location', 'child_sex', 'child_age_group']).value.describe()

# This is the amount by which we'd expect to underestimate CSMRisk due to total CSMRisk exceeding ACMRisk

## Cause-specific mortality ratio (after sampling)

In [ ]:
for cause in causes:
    for location in locations:
        plot_mortality_ratio(cause, location)

# these all look reasonable, though I don't know what is happening with other_causes in Pakistan
# this has been the case since model 19.1.x, though
# TODO: plot information about the precision/sample size

In [ ]:
# intervention checks

In [ ]:
# TODO: I don't get this variable name, nor the observer name
pop = read_results('anc_other', baseline_only=False)
pop.head()

In [ ]:
assert births.loc[(births.acs_availability) & (~births.acs_eligibility)]['value'].sum() == 0, 'ACS coverage among ACS ineligible population'
assert births.loc[(births.acs_availability) & (~births.cpap_availability)]['value'].sum() == 0, 'ACS coverage among population without CPAP coverage'
assert births.loc[(births.delivery_facility_type.isin(['home','none']))
                  &(births.acs_availability)]['value'].sum() == 0, 'ACS coverage among home births and/or partial term pregnancies'

In [ ]:
cols = ['location','input_draw','scenario','delivery_facility_type']
acs_cov = (births.loc[births.acs_eligibility].groupby(cols + ['acs_availability'])['value'].sum()
       /births.loc[births.acs_eligibility].groupby(cols)['value'].sum())
acs_cov = acs_cov.groupby([x for x in cols if x != 'input_draw'] + ['acs_availability']).describe(percentiles=[0.025,0.975]).reset_index()
acs_cov = acs_cov.loc[(acs_cov.acs_availability) & (acs_cov.delivery_facility_type.isin(['BEmONC','CEmONC']))]
acs_cov

In [ ]:
births.loc[births.acs_eligibility]['value'].sum().sum()

In [ ]:
cols = ['location','input_draw','scenario','delivery_facility_type']
cpap_cov = (births.groupby(cols + ['cpap_availability'])['value'].sum()
       /births.groupby(cols)['value'].sum())
cpap_cov = cpap_cov.groupby([x for x in cols if x != 'input_draw'] + ['cpap_availability']).describe(percentiles=[0.025,0.975]).reset_index()
cpap_cov = cpap_cov.loc[(cpap_cov.cpap_availability) & (cpap_cov.delivery_facility_type.isin(['BEmONC','CEmONC']))]
cpap_cov

# This is looking a bit low?
# coverage docs are here: https://vivarium-research.readthedocs.io/en/latest/models/intervention_models/neonatal/cpap_intervention.html#id6
# BEmONC should be 7.5%, CEmONC 39.3%
# TODO: Plot coverage for both ACS and CPAP

In [ ]:
deaths_by_intervention_status = (
    deaths
        .groupby(['input_draw','scenario','neonatal_burden_observer_cause_of_death','acs_eligibility','cpap_availability', 'preterm_birth'])
        ['value'].sum()
)
starting_population_by_intervention_status = (
    births.loc[births.pregnancy_outcome=='live_birth']
        .groupby(['input_draw','scenario','acs_eligibility','cpap_availability', 'preterm_birth'])
        ['value'].sum()
)
mortality_risk = (deaths_by_intervention_status / starting_population_by_intervention_status)
mortality_risk

In [ ]:
mort_acs = (deaths.loc[(deaths.acs_availability) & (deaths.acs_eligibility)
    &(deaths.delivery_facility_type=='CEmONC')].groupby(['input_draw','neonatal_burden_observer_cause_of_death'])['value'].sum()
            / births.loc[(births.acs_availability) & (births.acs_eligibility)    
    &(births.delivery_facility_type=='CEmONC')].groupby('input_draw')['value'].sum())
mort_no_acs = (deaths.loc[(~deaths.acs_availability) & (deaths.acs_eligibility)
    &(deaths.delivery_facility_type=='CEmONC')].groupby(['input_draw','neonatal_burden_observer_cause_of_death'])['value'].sum()
            / births.loc[(~births.acs_availability) & (births.acs_eligibility)
    &(births.delivery_facility_type=='CEmONC')].groupby('input_draw')['value'].sum())
rr_acs = mort_acs / mort_no_acs
rr_acs.groupby('neonatal_burden_observer_cause_of_death').describe()

# RR = 0.84 (95% CI 0.72-0.97) this is the ACS RR... but by definition everyone with ACS also has CPAP
# so the target is actually that multiplied by CPAP effect of 0.53 (95% CI 0.34-0.83).

# for a summary measure of 0.44, which we are fairly close to

# not sure why we are seeing RR values > 1 for preterm without RDS, sepsis, and other causes
# could it be something to do with a fractional decrease in the competing causes of deaths
# like we don't actually avert a death due to RDS, but we rather change the cause of death from RDS to another cause?

# that's my best guess here, but maybe we should look into it a bit more

In [ ]:
mort_cpap = (deaths.loc[(deaths.cpap_availability) & (~deaths.acs_eligibility) 
            & (deaths.preterm_birth) & (deaths.delivery_facility_type=='CEmONC')].groupby(['input_draw','neonatal_burden_observer_cause_of_death'])['value'].sum()
            / births.loc[(births.cpap_availability) & (~births.acs_eligibility)
                & (births.preterm_birth)&(births.delivery_facility_type=='CEmONC')].groupby('input_draw')['value'].sum())
mort_no_cpap = (deaths.loc[(~deaths.cpap_availability) & (~deaths.acs_eligibility) 
    & (deaths.preterm_birth)&(deaths.delivery_facility_type=='CEmONC')].groupby(['input_draw','neonatal_burden_observer_cause_of_death'])['value'].sum()
            / births.loc[(~births.cpap_availability) & (~births.acs_eligibility) 
                & (births.preterm_birth)&(births.delivery_facility_type=='CEmONC')].groupby('input_draw')['value'].sum())
rr_cpap = mort_cpap / mort_no_cpap
rr_cpap.groupby('neonatal_burden_observer_cause_of_death').describe()

# target CPAP effect of 0.53 (95% CI 0.34-0.83).
# looks good!
# but we do still see some elevated risk due to other causes...
# I think maybe due to the same issue discussed in the notes above